project:
  type: book
  output-dir: _book

book:
  title: "Reproducible Research Using R"
  author: "Christian Martinez"
  date: "2026-02-01"
  chapters:
    - index.qmd
    - chapters/01-Introduction-To-R.qmd
    - chapters/02-Introduction-To-tidyverse.qmd
    - chapters/03-Visualizations.qmd
    - chapters/04-Comparing-Two-Groups.qmd
    - chapters/05-Comparing-Multiple-Groups.qmd
    - chapters/06-Analyzing-Categorical-Data.qmd
    - chapters/07-Correlation.qmd
    - chapters/08-Linear-Regression.qmd
    - chapters/09-Logistic-Regression.qmd
    - chapters/10-Reproducible-Reporting.qmd
  appendices:
    - chapters/11-Appendix.qmd
    - chapters/12-downloading-installing-r-rstudio.qmd
    - chapters/13-Reproducible-Reporting-R-Markdown.qmd
    - chapters/14-Package-References.qmd
    - chapters/15-References.qmd


bibliography: bibliography/packages.bib
link-citations: true
number-sections: true

format:
  html:
    theme:
      - cosmo
      - brand
    code-copy: true
    code-summary: "Show the code"
    toc: true
    number-sections: true

execute:
  freeze: auto
  warning: false

editor: visual
