{
  "hash": "a7ca1c14f6e2b73911e916fadab0d879",
  "result": {
    "engine": "knitr",
    "markdown": "# Comparing Two Groups: Data Wrangling, Visualization, and t-Tests {#sec-two-means}\n\n## Introduction {#sec-intro-two-means}\n\nA tale as old as time. You have two different groups, and you want to really figure out not only if there is a difference, but also which is best. In New York City, this question materializes as Mets vs Yankees (Mets obviously).\n\nWhen you have two different groups with a numeric data point, one of the first (and best) things to do is to **compare the two means**. There is more to uncover than just seeing if there is a difference between the actual means, which is exactly what we are going to be covering today.\n\n::: callout-note\n### In this lesson, we will be answering the question:\n\n*Do the Mets or Yankess score a significantly different amount of runs in their games?*\n:::\n\nNot only will we be answering this question, but we’ll also walk through a complete workflow for comparing two groups. Starting from creating and reshaping data, we will move to visualizing differences, then to formally testing whether those differences are statistically meaningful. While this chapter uses baseball teams as the example, the same workflow applies to any two groups you might want to compare.\n\n## Learning Objectives {#sec-means-objectives}\n\nBy the end of this chapter, you will be able to:\n\n- Create simple data frames in R to represent grouped numeric data\n- Combine datasets by binding rows and joining tables using base R and tidyverse tools\n- Calculate and interpret group means using `mean()`\n- Visualize differences between two groups using appropriate plots (e.g., boxplots with jittered points)\n- Conduct and interpret an independent samples *t-test* using `t.test()`\n- Evaluate statistical significance using p-values and distinguish statistical significance from differences in averages\n\n## Creating a Sample Dataset {#sec-creating-datasets}\n\nThere are many different ways to get data into R. The most common are:\n\n- Loading an excel file or CSV\n- Calling data into R using an API\n- Loading data from a particular package (see chapter 7)\n\nWhat happens if you do not have data to insert into R? What if you want to **create** your own data in R to run analyses, merge, and graph?\n\nR makes it very simple to do exactly that! Using the automatically installed command `data.frame` R makes it possible to make your very own data frame with whatever you want inside. Here, we are going to create two datasets:\n\n1.  mets: This is going to be a data frame with 10 rows, each row being a different game, and the number of runs scored by the *Mets* in that game.\n2.  yankees: This is going to be a data frame with 10 rows, each row being a different game, and the number of runs scored by the *Yankees* in that game.\n\nIn this scenario, we can imagine that for whatever reason, we are unable or do not want to upload any data to R, but instead, create the data for ourselves. We will create our tables using 2025 Major League Baseball (MLB) data, and will have two columns:\n\n1.  Game: A number representing which game it is.\n2.  Score: The total runs the respective team scored in that game.\n\nTo summarize, we will be taking the scores from the first 10 Yankees games and the first 10 Mets games and creating a data frame with our data, and utilizing similar techniques introduced in @sec-intro-dataframes-creating.\n\n\n::: {#tbl-creating-mets-data .cell}\n\n```{.r .cell-code}\nmets <- data.frame(\n  Game = c(1,2,3,4,5,6,7,8,9,10),\n  Mets_Score = c(4,20,12,5,3,9,9,10,4,2)) # This is where we manually put our numbers in\n\nhead(mets) # This calls the first 6 rows of the data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Game Mets_Score\n1    1          4\n2    2         20\n3    3         12\n4    4          5\n5    5          3\n6    6          9\n```\n\n\n:::\n:::\n\n\n\n::: {#tbl-creating-yankees-data .cell}\n\n```{.r .cell-code}\nyankees <- data.frame(\n  Game = c(1:10), # The colon tells R \"any number between 1 and 10.\"\n  Yankees_Score = c(3,8,2,3,2,6,5,3,2,7))\n\ntail(yankees) # This calls the last 6 rows of the data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Game Yankees_Score\n5     5             2\n6     6             6\n7     7             5\n8     8             3\n9     9             2\n10   10             7\n```\n\n\n:::\n:::\n\n\nPerfect! We created two different data frames, *mets* and *yankees* with each having the two columns we were looking for.\n\nTo get more practice, let's do it again, but instead, we will do it with the next ten games of the 2025 season.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmets_second_ten <- data.frame(\n  Game = c(11:20),\n  Mets_Score = c(10,0,7,1,8,5,3,3,4,1))\n\nyankees_second_ten <- data.frame(\n  Game = c(11:20),\n  Yankees_Score = c(0,4,1,8,4,4,4,4,6,1))\n```\n:::\n\n\nNow, we successfully have datasets for the first 10 and first 20 games of the 2025 MLB season for both the Mets and the Yankees.\n\n## Merging Data {#sec-merging-data}\n\nWhat if we want our two datasets together?\n\n### Binding our data {#sec-binding-rows}\n\nWe have data for the first 20 games for the mets and yankees but they're split into the first 10 and second 10 games. What if we want to see all 20 games for each individual team? We can use a command in base R called `rbind`. The r stands for \"rows\" so this command is literally telling R to \"bind the rows.\"\n\n::: callout-note\n#### When it comes to rbind:\n\n*It only works when the column names in the binding datasets are the same.*\n:::\n\nWhen combining datasets, no matter which method, it is imperative that we check our data before and after to make sure the combining process worked how we anticipated. In this case, each of our original datasets contain 10 rows, which means our combined datasets should have 20 rows. We will be checking using `nrow`, and any number besides 20 means that there is an issue.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mets\nnrow(mets) # Seeing how many rows are in mets\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(mets_second_ten) # Seeing how many rows are in mets_second_ten\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n\n```{.r .cell-code}\nmets_all <- rbind(mets, mets_second_ten) # Combining the rows of mets and mets_second_ten\n\nnrow(mets_all) # Seeing how many rows are in mets_all\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20\n```\n\n\n:::\n\n```{.r .cell-code}\n# Yankees\nnrow(yankees)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(yankees_second_ten)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n\n```{.r .cell-code}\nyankees_all <- rbind(yankees, yankees_second_ten)\n```\n:::\n\n\nSuccess! Both of our datasets have 20 rows.\n\n### Joining Data {#sec-joining-data}\n\nOur two datasets, mets_all and yankees_all now have the data from the first 20 games of the 2025 MLB season, since we successfully combined our data. Now, what if we want one dataset that had the scores of each of the first 20 games for the Mets and Yankees?\n\nThere are a few different ways to do this. The first is to use the `merge` command which is part of base R. To check that our data has merged successfully, we need to make sure there are 20 rows and 3 columns: Game, Mets_Score, and Yankees_Score.\n\n\n::: {#tbl-baseball-merge .cell tbl-cap='The combined baseball dataset in wide format, featuring game-by-game scores for both the Yankees and the Mets.'}\n\n```{.r .cell-code}\nbaseball_data <- merge(yankees_all, mets_all, by = \"Game\")\n\nbaseball_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Game Yankees_Score Mets_Score\n1     1             3          4\n2     2             8         20\n3     3             2         12\n4     4             3          5\n5     5             2          3\n6     6             6          9\n7     7             5          9\n8     8             3         10\n9     9             2          4\n10   10             7          2\n11   11             0         10\n12   12             4          0\n13   13             1          7\n14   14             8          1\n15   15             4          8\n16   16             4          5\n17   17             4          3\n18   18             4          3\n19   19             6          4\n20   20             1          1\n```\n\n\n:::\n:::\n\n\nFantastic! We now have one complete dataset with the scores of the Mets and Yankees in the first 20 games.\n\n#### Using SQL Joins {#sec-sql-joins}\n\nWe previously used the `merge` command, however, R also allows for SQL code! Here is a quick overview of the main joins using SQL in R:\n\n- inner_join: Keeps only rows that match in both datasets\n  - Overlap\n- full_join: Keeps all rows from both datasets, matching when possible\n  - Everything\n- left_join: Keeps all rows from the left dataset, and matches from the right when possible\n- All left\n- right_join: Keeps all rows from the right dataset, and matches from the left when possible\n  - All right\n- anti_join: Keeps rows from the left dataset that do NOT appear in the right\n- What's missing\n\n\n::: {.cell}\n::: {.cell-output-display}\n![An image of the different sql joins and their outcomes.](../images/sql.png){#fig-sql-image fig-alt='An image of the different sql joins and their outcomes.' width=768}\n:::\n:::\n\n\nIn this case, we are going to use `inner_join`, since we know that both of our datasets have the same 20 games.\n\n\n::: {#tbl-baseball-sql .cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nbaseball_data_sql <- inner_join(yankees_all, mets_all, by = \"Game\")\n\nnrow(baseball_data_sql) # Checks the number of rows\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20\n```\n\n\n:::\n\n```{.r .cell-code}\nncol(baseball_data_sql) # Checks the number of columns\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n\n```{.r .cell-code}\nbaseball_data_sql\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Game Yankees_Score Mets_Score\n1     1             3          4\n2     2             8         20\n3     3             2         12\n4     4             3          5\n5     5             2          3\n6     6             6          9\n7     7             5          9\n8     8             3         10\n9     9             2          4\n10   10             7          2\n11   11             0         10\n12   12             4          0\n13   13             1          7\n14   14             8          1\n15   15             4          8\n16   16             4          5\n17   17             4          3\n18   18             4          3\n19   19             6          4\n20   20             1          1\n```\n\n\n:::\n:::\n\n\nOne of the beautiful things in R is that you can get the same results using different code - just like we did here. Our two baseball datasets are identical even though we used two different commands to get them. This is an example of how **R puts the r in Artist.**\n\n### Wide Format {#sec-wide-format}\n\nRight now, our data is considered **wide** format, that is, there are 20 rows, and separate columns for the scores of the Yankees and scores of the Mets. In some cases, we may need our data to be in a long format. In this case, there will be 40 rows instead of 20, since each Yankees score and each Mets score will represent a row, instead of each **game** representing a row.\n\nUsing the `pivot_longer` function from the `tidyverse` package, we can turn our data from wide to long.\n\n\n::: {#tbl-baseball-pivot-longer .cell}\n\n```{.r .cell-code}\n# Lets say we want to turn out data from wide format into long format, so we can run \nbaseball_data_long <- baseball_data |> pivot_longer(cols = c(Yankees_Score, Mets_Score),\n                                                    names_to = \"Team\",\n                                                    values_to = \"Score\")\n\nnrow(baseball_data_long)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 40\n```\n\n\n:::\n\n```{.r .cell-code}\nbaseball_data_long\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 40 × 3\n    Game Team          Score\n   <int> <chr>         <dbl>\n 1     1 Yankees_Score     3\n 2     1 Mets_Score        4\n 3     2 Yankees_Score     8\n 4     2 Mets_Score       20\n 5     3 Yankees_Score     2\n 6     3 Mets_Score       12\n 7     4 Yankees_Score     3\n 8     4 Mets_Score        5\n 9     5 Yankees_Score     2\n10     5 Mets_Score        3\n# ℹ 30 more rows\n```\n\n\n:::\n:::\n\n\n### Long Format (Reverse Demo) {#sec-long-format}\n\nOur original baseball_data (and baseball_data_sql) are in wide format already so we don't have to do this, but just in case you ever start with long data and want to convert it to wide, here is some code to help. Below, we are turning our baseball_data_long into a wide format.\n\n\n::: {#tbl-baseball-pivot-wide .cell}\n\n```{.r .cell-code}\n# Lets say we want to turn out data from wide format into long format, so we can run \nbaseball_data_wide <- baseball_data_long |> pivot_wider(names_from = \"Team\",\n                                                    values_from = \"Score\")\nnrow(baseball_data_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20\n```\n\n\n:::\n\n```{.r .cell-code}\nbaseball_data_wide\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 3\n    Game Yankees_Score Mets_Score\n   <int>         <dbl>      <dbl>\n 1     1             3          4\n 2     2             8         20\n 3     3             2         12\n 4     4             3          5\n 5     5             2          3\n 6     6             6          9\n 7     7             5          9\n 8     8             3         10\n 9     9             2          4\n10    10             7          2\n11    11             0         10\n12    12             4          0\n13    13             1          7\n14    14             8          1\n15    15             4          8\n16    16             4          5\n17    17             4          3\n18    18             4          3\n19    19             6          4\n20    20             1          1\n```\n\n\n:::\n:::\n\n\n## Comparing Means {#sec-comparing-means}\n\nNow that we have our data all together, in both wide and long format, we are ready to start comparing means. First things first: we need to calculate the means!\n\n### Calculating the means {#sec-calculating-means}\n\nUsing the `mean` function, we can simply calculate the mean/s of our data. Just know that mean and average mean (pun intended) the same thing and are interchangeable words.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating the individual means of the teams scores, we can use our wide format\nyankees_average_score <- mean(baseball_data$Yankees_Score) \n\n# Note, we are saving this as a variable so it can be called anytime, but you could just run mean(baseball_data$Yankees_Score)\nyankees_average_score\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.85\n```\n\n\n:::\n\n```{.r .cell-code}\nmets_average_score <- mean(baseball_data$Mets_Score)\n# If we want to round our numbers, we can use the code below\n# mets_average_score<- round(mean(baseball_data$Mets_Score),0)\nmets_average_score\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculating the means of all the scores, we can use our long format\noverall_average <- mean(baseball_data_long$Score)\n\noverall_average\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.925\n```\n\n\n:::\n:::\n\n\nHere is a breakdown of the means:\n\n- Yankees Average Scores: 3.85\n- Mets Average Scores: 6\n- Overall Average Scores: 4.925\n\nIt isn't necessary, but let us take this time to round our means\n\nRight now, we can see that the Mets average runs scored is higher than *both* the Yankees and overall average scores. While we see that there is a difference, we do not know if this difference is *significant* or not. This is where a **t.test** comes into play.\n\nBefore running a t-test, it’s often helpful to visualize the data to see how much the two groups overlap. An excellent way to do this is to create a boxplot, first introduced in @sec-ggplot-boxplot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(baseball_data_long, aes(Team, Score)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_jitter(width = 0.15, alpha = 0.4, size = 1.5) +\n  coord_flip()+\n  labs(\n  title = \"Runs Scored by Team Across the First 20 Games\",\n  x = \"Team\",\n  y = \"Runs Scored\"\n  ) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![Distribution of runs scored by the New York Yankees and New York Mets across the first 20 games of the 2025 season. Boxplots summarize the central tendency and spread of scores for each team, while individual points represent runs scored in each game. This visualization highlights the overlap between groups, motivating the use of an independent samples *t*-test to evaluate whether observed differences in mean runs scored are statistically significant.](04-Comparing-Two-Groups_files/figure-html/fig-baseball-plot-1.png){#fig-baseball-plot width=672}\n:::\n:::\n\n\nThere has already been a lot of work done with our data, and through both visualizations and summary statistics, we have an idea of where our groups differ. The next step of comparing two means is to dive even deeper: statistics.\n\n### t.test {#sec-t-tests}\n\nA t-test compares the difference between two group means relative to the variability in the data. Depending on your data, you will either be running a **Paired** or **Unpaired** t.test:\n\n- Paired t-test: use when measurements come in matched pairs (same participant twice, same game for both teams).\n  - Example: Ten people first run a race just drinking water. Then, those same ten people run the same race but drinking coffee.\n- Unpaired t-test: use when the two groups are independent (different participants, no pairing).\n  - Example: Ten people drink water, then ten different people drink coffee, and all of them run a race at the same time.\n- Pairing is about the **design** of the data, not how the table looks.\n\n::: callout-tip\n#### Rule of thumb:\n\nIf you can draw a line connecting observations across groups (same person, matched pair, same unit measured twice), it’s paired.\n:::\n\nFor our data, we need to conduct an unpaired t.test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Unpaired t.test\nbaseball_t_test <- t.test(baseball_data$Yankees_Score, baseball_data$Mets_Score, paired = F)\n# From a structural standpoint, if we needed to run a paired t.test, all we would need to do is change \"paired = F\" to \"paired = T\"\n\nbaseball_t_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  baseball_data$Yankees_Score and baseball_data$Mets_Score\nt = -1.823, df = 27.274, p-value = 0.07928\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -4.568735  0.268735\nsample estimates:\nmean of x mean of y \n     3.85      6.00 \n```\n\n\n:::\n:::\n\n\n::: callout-tip\n#### If you are working with long data, you cal use the formula:\n\nt.test(y \\~ x, data = data_long)\n\nt.test(Score \\~ Team, data = baseball_data_long)\n:::\n\nThe output when we call baseball_t_test tells us something extremely important: p-value. When looking at a p-value, we are looking to see if it is above or below the 0.05 mark.\n\n- If p \\< 0.05: reject the null hypothesis (evidence of a difference)\n- If p ≥ 0.05: fail to reject the null (not enough evidence of a difference)\n\nSo, while the two averages are not the same, our p-value is 0.07928, which is above the 0.05 threshold. This means that there **is not** a statistical difference between the average runs scored in the first 20 games between the Yankees and Mets. Even though the Mets scored more runs on average, this difference was not statistically significant, reminding us that magnitude and statistical significance are not the same thing. In real research, this distinction matters. **Decisions should not be made on differences in averages alone.**\n\n## Key Takeaways {#sec-means-takeaways}\n\n- To create data frames in R, use the `data.frame` command.\n- To merge data in R, you can:\n  - Bind rows (`rbind()`)\n  - Join (merge or any of the SQL commands, depending on the desired outcome)\n- Use `pivot_longer()` to turn wide formatted data into long format\n- Use `pivot_wider()` to turn long formatted data into wide format\n- Just because the means/averages of two variables are different **does not mean** that they are statistically different.\n- To check to see if the difference between two means is statistically significant, perform a t.test using the `t.test()` command\n  - Depending on how the data is structured, this will either be a paired or unpaired t.test.\n\n## Checklist {#sec-means-checklist}\n\n### Data Creation & Import {#sec-checklist-create-import}\n\n- [ ] Loaded or created your datasets in R (data.frame, CSV, API, or package)\n- [ ] Inspected your data using `head()`, `str()`, or `summary()`\n- [ ] Combined datasets by rows using `rbind()` when appropriate\n- [ ] Joined datasets using `merge()` or a SQL-style join\n- [ ] Verified merges by checking row and column counts (`nrow()`, `ncol()`)\n- [ ] Reshaped data if needed using `pivot_longer()` or `pivot_wider()`\n\n### Comparing Two Means {#sec-checklist-means}\n\n- [ ] Calculated group means using `mean()`\n- [ ] Determined whether the design is paired or independent\n- [ ] Selected the correct t-test (paired or unpaired)\n- [ ] Ran the t-test using `t.test()`\n- [ ] Compared the p-value to the 0.05 threshold\n- [ ] Clearly stated your conclusion in plain language\n\n## Key Functions & Commands {#sec-means-key-functions}\n\nThe following functions and commands are introduced or reinforced in this chapter to support data restructuring, joining, and basic statistical comparison.\n\n- `data.frame()` *(base R)*\n  - Creates a data frame object for storing tabular data.\n- `rbind()` *(base R)*\n  - Combines multiple data frames by binding rows together.\n- `merge()` *(base R)*\n  - Joins two data frames together based on a shared key variable.\n- `inner_join()` *(dplyr)*\n  - Performs a SQL-style inner join, keeping only rows that match in both datasets.\n- `pivot_longer()` *(tidyr)*\n  - Converts data from wide format to long format.\n- `pivot_wider()` *(tidyr)*\n  - Converts data from long format back to wide format.\n- `mean()` *(base R)*\n  - Calculates the average value of a numeric variable.\n- `t.test()` *(stats)*\n  - Performs a hypothesis test to evaluate whether the means of two groups differ significantly.\n\n## Example APA-style Write-up {#sec-means-apa}\n\nThe following example demonstrates one acceptable way to report a comparison of two means in APA style.\n\n**Independent Samples *t*-Test**\n\nAn independent samples $t$-test was conducted to examine whether the average number of runs scored differed between the New York Yankees and the New York Mets across the first 20 games of the season. The Mets scored more runs on average ($M = 6.00, SD = 4.79$) than the Yankees ($M = 3.85, SD = 2.13$); however, this difference was not statistically significant, $t(25.9) = 1.80, p = .084$. Although the Mets had a higher mean score, this result indicates insufficient evidence that the teams differed in average runs scored.\n\n::: callout-note\n### Reporting Note:\n\nThe degrees of freedom ($25.9$) reflect a Welch’s $t$-test, which is the default in R and does not assume equal variances between groups.\n:::\n\n## 💡 *Reproducibility Tip:* {#sec-merge-tip}\n\nMerging data is a *crucial* step in many analysis projects. Whether you are using SQL-style joins or base R functions, it is essential to check the structure of your data before and after every merge.\n\nA simple but powerful habit is to verify the number of rows using functions like `nrow()`. Joins that are not specified correctly can lead to what are often called “data explosions,” where a dataset unexpectedly grows. A incorrectly specified merge can easily take a dataset from 1,000 rows to 3,000,000, when only 1,000 were expected.\n\nChecking row counts before and after a merge helps ensure that the join behaved as intended and can save your analysis (and your computer) from serious errors.\n\nYour analysis cannot be reproducible if its underlying data are incorrect. Developing the habit of validating merges is especially important here, as this is the first chapter where data merging is introduced.\n",
    "supporting": [
      "04-Comparing-Two-Groups_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}