{
  "hash": "31759daa191f194de30ba430b9680da9",
  "result": {
    "engine": "knitr",
    "markdown": "# Comparing Multiple Groups {#sec-anova}\n\n## Introduction {#sec-intro-anova}\n\nIn @sec-two-means we learned what to do when we have two groups and want to compare their means. However, not every situation only has two groups.\n\nPicture this: You just ran an experiment and had three groups. You want to see if they performed differently, but do not know how. You learned in the last chapter that if we had two groups, we could run a t.test, but now you have one more. This sounds like the perfect opportunity to run an **Analysis of Variance** (ANOVA). An **ANOVA** tests whether the means of three or more groups are significantly different from one another. It does this by comparing the variance between groups to the variance within groups.\n\n::: callout-note\n### In this lesson, we will explore how to use **ANOVAs** to answer the question:\n\n*How do studying methods influence memory scores?*\n:::\n\nWe will create a dataset called `memory`, which includes students’ method of studying and their memory scores.\n\n## Learning Objectives {#sec-anova-objectives}\n\nBy the end of this chapter, you will be able to:\n\n- Create a reproducible dataset in R.\n- Conduct one-way and two-way ANOVAs.\n- Interpret ANOVA output (F, p, SS, MS).\n- Run post-hoc comparisons with Tukey’s HSD.\n- Compare models using AIC.\n\nAlthough the statistical method used here is called ANOVA, the goal of this chapter is to understand how group comparisons scale beyond two groups.\n\n## Creating Our Data {#sec-creating-data-anova}\n\nIn this chapter, we are not going to be loading any previously captured data. Instead, we will be utilizing R to help create our own data. Our data is going to contain two variables:\n\n1.  method: identified their studying methods, either flashcards, rereading the material, or taking practice tests\n2.  score: how well they scored on a memory test after studying.\n\nWith our focus being reproducibility, how can we manage to make sure that the data we create here is the same data you will create? In R, we do this by using the `set.seed` command. What this does is makes sure the \"random\" data creation is the same no matter who is creating the data.\n\nImagine we had a deck of cards. We need to shuffle them before we deal them to our players. `set.seed()` is the equivalent to that deck of cards being shuffled in a specific order, that way, if it is shuffled that way every single time, each player is going to be dealt the same cards.\n\n::: callout-important\n### With regards to `set.seed()`\n\nAs long as we put the same number in `set.seed()` then the same data will be created.\n:::\n\nNext, we can use the `rnorm()` command to dictate quantity, mean, and standard deviation of each.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nset.seed(123)  # ensures reproducibility\n\nmemory <- tibble(\n  method = rep(c(\"Flashcards\", \"Rereading\", \"Testing\"), each = 20),\n  score = c(\n    rnorm(20, mean = 75, sd = 8),  # Flashcards group\n    rnorm(20, mean = 70, sd = 9),  # Rereading group\n    rnorm(20, mean = 85, sd = 7)   # Testing group\n  )\n)\n\nglimpse(memory)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 60\nColumns: 2\n$ method <chr> \"Flashcards\", \"Flashcards\", \"Flashcards\", \"Flashcards\", \"Flashc…\n$ score  <dbl> 70.51619, 73.15858, 87.46967, 75.56407, 76.03430, 88.72052, 78.…\n```\n\n\n:::\n:::\n\n\nWe have successfully created our first dataset!\n\n## Descriptive Statistics {#sec-anova-descriptive-stats}\n\nNow that we have our data, let us do some digging to get some descriptive statistics regarding central tendency. As done before, we can create a summarized table.\n\n\n::: {#tbl-summary_table .cell tbl-cap='A summarized table grouped by the method, with average, standard deviation, and the number of rows.'}\n\n```{.r .cell-code}\n# Creating a summarizing table\nmemory_summarized <- memory |>\n  group_by(method) |>\n  summarize(\n    mean_score = mean(score),\n    sd_score = sd(score),\n    n = n()\n  )\n\nmemory_summarized\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  method     mean_score sd_score     n\n  <chr>           <dbl>    <dbl> <int>\n1 Flashcards       76.1     7.78    20\n2 Rereading        69.5     7.47    20\n3 Testing          85.7     6.70    20\n```\n\n\n:::\n:::\n\n\nInstead of writing all of the code manually, we can utilize the `favstats()` command from the `mosaic` package (@R-mosaic).\n\n\n::: {#tbl-favstats .cell tbl-cap='A summarized table using the function favstats() instead of summarize().'}\n\n```{.r .cell-code}\nlibrary(mosaic)\n\nfavstats(score ~ method, data = memory)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      method      min       Q1   median       Q3       max     mean       sd  n\n1 Flashcards 59.26706 71.05157 75.95988 79.38981  89.29531 76.13299 7.781323 20\n2  Rereading 54.81976 64.14098 68.74051 76.49688  81.28433 69.53869 7.469448 20\n3    Testing 74.15873 82.06821 84.75004 89.43416 100.18269 85.74540 6.701384 20\n  missing\n1       0\n2       0\n3       0\n```\n\n\n:::\n:::\n\n\nSome things we now see:\n\n1.  Testing has the highest minimum and maximum values in comparison to the other two methods\n2.  Testing has the highest median\n3.  Testing has the highest mean.\n4.  Testing has the lowest standard deviation\n5.  There are no missing values\n\nThese are early indications that testing is the best studying method if we want the highest memory scores.\n\n## Visualizing Relationships {#sec-anova-viz}\n\nWhen we have categorical and numeric data, there are two visualizations that are extremely relevant when visualizing our data: boxplots and bar charts (see @sec-ggplot-bar for a quick review on bar charts).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(memory, aes(x = method, y = score, fill = method)) +\n  geom_boxplot(alpha = 0.7) +\n  labs(\n    title = \"Memory Test Scores by Study Technique\",\n    x = \"Study Technique\",\n    y = \"Memory Test Score\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Boxplots showing the distribution of memory test scores for each study technique, highlighting differences in central tendency and variability across groups.](05-Comparing-Multiple-Groups_files/figure-html/fig-plots-anova-1.png){#fig-plots-anova width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmemory |>\n  group_by(method) |>\n  summarize(mean_score = mean(score)) |>\n  ggplot(aes(x = method, y = mean_score, fill = method)) +\n  geom_col() +\n  geom_text(aes(label = round(mean_score, 1)), vjust = -0.5) + # adds the means to bars\n  labs(\n    title = \"Average Memory Score by Study Technique (ANOVA Means)\",\n    x = \"Study Technique\",\n    y = \"Average Score\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Average memory test scores by study technique. While differences in group means are apparent, statistical significance is assessed using a one-way ANOVA rather than visual inspection alone.](05-Comparing-Multiple-Groups_files/figure-html/fig-anova-means-plot-1.png){#fig-anova-means-plot width=672}\n:::\n:::\n\n\n## Running a T.Test {#sec-anova-t-test}\n\nIn @sec-t-tests, we learned how to run a t.test to better understand the difference in means between two groups. If we try to run a t.test on our data now...\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Last chapter we learned how to run a t.test. Let's try it out now.\ntry(t.test(score ~ method, data = memory))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nError in t.test.formula(formula, data = data, ...) : \n  grouping factor must have exactly 2 levels\n```\n\n\n:::\n:::\n\n\nIt does not work! The reason being is that while t.test compare means, they are only able to calculate the difference between **two** means. When there are more than two, t.tests fail. We must instead conduct an *ANOVA.*\n\n## One-Way ANOVA {#sec-one-way-anova}\n\nWe have some idea, from both our visuals and descriptive statistics that the testing studying technique is better than the other two. However, while we do know that the means are different, we do not know if the difference between the means of the three techniques is statistically significant or not. We can not use t.tests because there are more than two groups. In order to uncover whether the difference between the studying technique means is statistically significant or not, we now conduct an ANOVA.\n\nTo do this, we can use the `aov` command which is very similar to `t.test`. The formula used is:\n\ndependent_variable \\~ independent_variable, data = your_data\n\nTo really bring it to the next level, we can also call the `supernova` command from the supernova package.\n\n\n::: {#tbl-anova .cell tbl-cap='One-way ANOVA Summary Table: Studying Method and Memory Scores'}\n\n```{.r .cell-code}\n# running an anova\nanova_model <- aov(score ~ method, data = memory)\n\nsummary(anova_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nmethod       2   2657  1328.5   24.72 1.87e-08 ***\nResiduals   57   3064    53.8                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWe can also utilize the `supernova()` function, from the `supernova` package (@R-supernova), for a cleaner output.\n\n\n::: {#tbl-anova-supernova .cell tbl-cap='One-way ANOVA Supernova Table: Studying Method and Memory Scores'}\n\n```{.r .cell-code}\nlibrary(supernova)\nsupernova(anova_model)  # clearer ANOVA table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Analysis of Variance Table (Type III SS)\n Model: score ~ method\n\n                               SS df       MS      F   PRE     p\n ----- --------------- | -------- -- -------- ------ ----- -----\n Model (error reduced) | 2656.938  2 1328.469 24.716 .4644 .0000\n Error (from model)    | 3063.753 57   53.750                   \n ----- --------------- | -------- -- -------- ------ ----- -----\n Total (empty model)   | 5720.691 59   96.961                   \n```\n\n\n:::\n:::\n\n\nJust as the `aov` command should look similar, the output of running the anova should look familiar. Reviewing the data we get:\n\n- Sum of Squares (SS): the total amount of variation explained by each source\n  - Method SS - the amount of variation explained by the studying method - 2657\n  - Residual SS- the amount of variation explained by everything other than method - 3063\n  - The total is 5720, which means that **about 46% of all variation in scores is due to studying method.**\n- Df: degrees of freedom\n  - There are 2 degrees of freedom (3-1), since there are 3 studying methods\n- Mean square: SS ÷ Df.\n  - provides us with the average variability per degree of freedom.\n  - Mean Method SS = 2657 / 2 = 1328.5\n  - Mean Residuals SS = 3064 / 57 = 53.8\n  - There is more variation explained per degree of freedom by studying method vs everything else.\n- F value: how much larger the variation between groups is compared to the variation within groups\n- 24.72: there is more variation between the studying method groups than within each group.\n- pr(\\>F): the p-value\n  - It is lower than 0.05, meaning there is a statistically significant difference in memory scores based on studying technique.\n  - Hint: The number of \\* by the p-value indicates if it is significant or not. \\*\\*\\* is statistically significant.\n\nWith all of that, we can now conclude that there is a statistically significant difference in memory scores due to studying technique. While this tells us that the difference is significant, it does not tell us **what the difference between the techniques is.** Through visualizations and descriptive statistics, we think testing is the best method, but it is important to make sure.\n\n## Post-hoc Tests {#sec-post-hoc-anova}\n\nTo add to our ANOVA and descriptive statistics, we can run what is called *Post-hoc Tests.* These are meant to dive deeper into the ANOVA model. While an ANOVA model tells us **if** there is a statistically significant difference, Post-hoc Tests tell us **where** the difference is. The `TukeyHSD` command provides the insight.\n\n\n::: {#tbl-post-hoc .cell tbl-cap='Tukey’s Honest Significant Difference (HSD) Post-hoc Comparisons: Pairwise Mean Differences Between Study Techniques'}\n\n```{.r .cell-code}\nTukeyHSD(anova_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = score ~ method, data = memory)\n\n$method\n                          diff        lwr       upr     p adj\nRereading-Flashcards -6.594305 -12.173359 -1.015251 0.0167319\nTesting-Flashcards    9.612406   4.033352 15.191460 0.0003304\nTesting-Rereading    16.206711  10.627657 21.785765 0.0000000\n```\n\n\n:::\n:::\n\n\nWe have three different rows, with each studying technique compared to each other. The ‘diff’ column shows the mean difference between groups (Group 2 − Group 1).\n\n- Positive = first group has a higher mean.\n- Negative = first group has a lower mean.\n\nLooking here, we can see that testing has a higher mean than both flashcards and rereading when compared against the two. We also look at the p adj, which is just the p-value. All three are statistically significant, specifically the two related to testing.\n\nWe can visualize this difference in mean comparisons using the `plot` command in base R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(TukeyHSD(anova_model))\n```\n\n::: {.cell-output-display}\n![Tukey’s HSD post-hoc comparison plot showing confidence intervals for pairwise mean differences between study techniques. Each horizontal line represents a comparison between two groups; intervals that do not cross zero indicate statistically significant differences following a significant ANOVA.](05-Comparing-Multiple-Groups_files/figure-html/fig-post-hoc-plot-1.png){#fig-post-hoc-plot width=672}\n:::\n:::\n\n\nTaking all this into consideration:\n\n1.  Descriptive statistics show that the mean of Testing is higher than the other techniques.\n2.  The ANOVA results show that there is a statistically significant difference between the means of the different techniques.\n3.  The Post-hoc test results show that testing has higher means than Flashcards and Rereading, and that those differences are statistically significant.\n\nAll of this brings us to the conclusion: **The Testing studying technique provides the highest memory exam scores.**\n\n## Adding a Second Factor (Two-Way ANOVA) {#sec-anova-second-factor}\n\nWe have done a fantastic job of identifying the best studying technique out of the three in order to get the highest memory exam scores. In life, there are typically more than just two variables. What if there was another variable in this study? For instance, what if each person's caffeine level while studying for the memory exam was also taken into consideration. Maybe caffeine level had an influence on how well they studied, and in turn impacts their memory score. And if that is taken into account, is that a better model for explaining differences in memory scores?\n\nTo test this out, let's first create the caffeine column using a similar technique to how we created our data in the beginning.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Let's say we also measured caffeine intake (low vs high)\nset.seed(42)\nmemory2 <- memory |>\n  mutate(\n    caffeine = rep(c(\"Low\", \"High\"), times = 30))\n```\n:::\n\n\nNow that we’ve established that study method affects memory, let’s ask a new question: does caffeine level also play a role? This moves us from a one-way ANOVA (one independent variable) to a two-way ANOVA (two independent variables, or factors)\n\n\n::: {#tbl-interaction .cell tbl-cap='Two-way ANOVA Supernova Table: Studying Method, Memory Scores, and Caffeine'}\n\n```{.r .cell-code}\n# To see the interaction between method and caffeine levels, we add a *\nanova_2 <- aov(score ~ method * caffeine, data = memory2)\n\nsupernova(anova_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Analysis of Variance Table (Type III SS)\n Model: score ~ method * caffeine\n\n                                         SS df      MS      F   PRE     p\n --------------- --------------- | -------- -- ------- ------ ----- -----\n           Model (error reduced) | 2777.807  5 555.561 10.194 .4856 .0000\n          method                 | 1746.636  2 873.318 16.025 .3725 .0000\n        caffeine                 |   39.360  1  39.360  0.722 .0132 .3992\n method:caffeine                 |  117.439  2  58.720  1.077 .0384 .3477\n           Error (from model)    | 2942.885 54  54.498                   \n --------------- --------------- | -------- -- ------- ------ ----- -----\n           Total (empty model)   | 5720.691 59  96.961                   \n```\n\n\n:::\n:::\n\n\nInterestingly, when we go to the p-values, we see that neither caffeine nor the interaction (how caffeine influences method) are statistically significant. This is a huge indication that caffeine does not have any impact on memory scores whatsoever. We can visualize this\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(memory2, aes(x = method, y = score, color = caffeine, group = caffeine)) +\n  stat_summary(fun = mean, geom = \"point\") +\n  stat_summary(fun = mean, geom = \"line\") +\n  labs(title = \"Interaction of Study Method and Caffeine\",\n       x = \"Study Method\",\n       y = \"Mean Memory Score\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Interaction plot between Study Method and Caffeine Level. The near-parallel lines indicate that caffeine does not significantly alter the effectiveness of different study methods.](05-Comparing-Multiple-Groups_files/figure-html/fig-interaction-plot-1.png){#fig-interaction-plot width=672}\n:::\n:::\n\n\n::: callout-tip\n### What the p-value is actually telling you:\n\nIn the graph above, we see that the lines for both high and low are nearly parallel. This gives you an indication that caffeine does not have a significant impact on study method\n:::\n\nThe results from the ANOVA are impactful, and since we now have two different ANOVA models, we can compare the models.\n\n## Model Comparison With AIC {#sec-aic-anova}\n\nUsing the `aictab()` function from the `AICcmodavg` package (@R-AICcmodavg), we can compare the one-way ANOVA model with the two-way ANOVA model to see what is the overall better model of understanding differences in memory scores.\n\n\n::: {#tbl-model-comparison .cell tbl-cap='Model Comparison using AIC: Evaluating One-Way vs. Two-Way ANOVA for Memory Performance'}\n\n```{.r .cell-code}\n# Compare one-way vs. two-way models\nlibrary(AICcmodavg)\nmodel.set <- list(\n  aov(score ~ method, data = memory2),\n  aov(score ~ method * caffeine, data = memory2))\n\nmodel.names <- c(\"One-way\", \"Two-way\")\n\naictab(model.set, modnames = model.names)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel selection based on AICc:\n\n        K   AICc Delta_AICc AICcWt Cum.Wt      LL\nOne-way 4 414.98       0.00   0.92   0.92 -203.13\nTwo-way 7 419.99       5.01   0.08   1.00 -201.92\n```\n\n\n:::\n:::\n\n\nWe will review model comparisons in more detail in @sec-more-variables. For right now, we can just look at the AICc values. AIC values don’t test significance — they measure relative model quality. The general rule of thumb is that the lower the value, the better the model. In this case, the one-way ANOVA is the better model, confirming what the ANOVA results themselves also described.\n\n## Key Takeaways {#sec-anova-takeaways}\n\n- ANOVA (Analysis of Variance) is used to compare **means across more than two groups**.\n- A **significant F-statistic** indicates that at least one group mean is different.\\\n- **Post-hoc tests** (like Tukey’s HSD) reveal **which** groups differ from each other.\\\n- The **Sum of Squares (SS)** separates total variation into between-group and within-group sources.\\\n- The **Mean Square (MS)** is the average variation per degree of freedom (SS ÷ df).\\\n- The **F value** is a ratio comparing between-group to within-group variability.\\\n- **Two-way ANOVA** adds an additional factor (e.g., caffeine level) to test main effects and interactions.\n- **AIC** (Akaike Information Criterion) helps compare models — *lower values indicate better fit*.\\\n- Always visualize your data before and after running ANOVA to confirm patterns in group means.\n- Reproducibility matters — use `set.seed()` whenever you simulate or randomize data.\n\n## Checklist {#sec-anova-checklist}\n\n**When running an ANOVA, have you:**\n\n- [ ] Verified that your **dependent variable is numeric** and your **independent variable(s) are categorical**?\\\n- [ ] Created or imported your dataset reproducibly (used `set.seed()` if simulated)?\\\n- [ ] Summarized descriptive statistics for each group?\\\n- [ ] Visualized group means and distributions using boxplots or bar charts?\\\n- [ ] Fit your model using `aov()` or `supernova()`?\\\n- [ ] Interpreted the **F statistic**, **df**, and **p-value**?\\\n- [ ] Conducted **post-hoc tests** (e.g., `TukeyHSD`) to identify where differences lie?\\\n- [ ] Checked **residuals** or **assumptions** (optional but good practice)?\\\n- [ ] Added a **second factor** if relevant (two-way ANOVA)?\\\n- [ ] Compared models using **AIC** or another fit statistic?\\\n- [ ] Written a clear interpretation that answers your research question?\n\n## Key Functions & Commands {#sec-anova-key-functions}\n\nThe following functions and commands are introduced or reinforced in this chapter to support analysis of variance (ANOVA), post-hoc testing, and model comparison.\n\n- `set.seed()` *(base R)*\n  - Ensures reproducibility when generating random data.\n- `rnorm()` *(stats)*\n  - Generates random values from a normal distribution with a specified mean and standard deviation.\n- `aov()` *(stats)*\n  - Fits one-way and two-way analysis of variance (ANOVA) models.\n- `summary()` *(base R)*\n  - Produces summaries of ANOVA model results, including F statistics and p-values.\n- `supernova()` *(supernova)*\n  - Displays ANOVA results in a clear, structured table emphasizing sums of squares and variance explained.\n- `TukeyHSD()` *(stats)*\n  - Performs post-hoc pairwise comparisons following a significant ANOVA.\n- `plot()` *(base R)*\n  - Visualizes post-hoc comparison results, such as Tukey’s HSD confidence intervals.\n- `aictab()` *(AICcmodavg)*\n  - Compares competing statistical models using Akaike Information Criterion (AIC).\n\n## Example APA-style Write-up {#sec-anova-apa}\n\nThe following example demonstrates one acceptable way to report the results of a one-way analysis of variance (ANOVA) in APA style.\n\n**One-Way Analysis of Variance (ANOVA)**\n\nA one-way analysis of variance (ANOVA) revealed a significant effect of study method on memory test scores (see @tbl-anova-supernova), $F(2, 57) = 24.72, p < .001$. Post hoc Tukey’s HSD tests indicated that participants in the testing condition scored significantly higher than participants in the flashcards and rereading conditions. Mean scores (*M* ± *SD*) were 75.2 ± 8.1 for flashcards, 69.8 ± 9.0 for rereading, and 84.9 ± 7.1 for testing, demonstrating that the testing method produced the highest memory performance.\n\n## 💡 *Reproducibility Tip:* {#sec-anova-tip}\n\nWhen your analysis involves randomness-such as simulated data, resampling, or random assignment—always set a seed using `set.seed()`.\n\nBecause we used `set.seed(123)` when generating the data in this chapter, anyone who runs the code will obtain identical results. This ensures that differences in output are due to changes in code or assumptions, not randomness.\n\nSetting a seed is a simple but essential step for reproducible research, especially when teaching, sharing code, or revisiting an analysis later.\n\nIt does not matter what the seed is set to, as long as it is set to something!\n",
    "supporting": [
      "05-Comparing-Multiple-Groups_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}