{
  "hash": "9d67f865f7e5093b1f6b2a5e24afc419",
  "result": {
    "engine": "knitr",
    "markdown": "# Linear Regression {#sec-linear-reg}\n\n## Introduction {#sec-intro-linear-reg}\n\nIn this lesson, we will explore how to use **linear regression** to not only understand, but to also predict relationships between variables.\n\n::: callout-note\n### Everyone loves pizza (cowabunga!) and like many pizza establishments, we will be trying to answer the question:\n\n*Can we predict the amount of pizza sold based on its price?*\n:::\n\nWe'll use a dataset called `pizza_prices`, which contains weekly pizza sales and pricing data.\n\n## Learning Objectives {#sec-lin-reg-objectives}\n\nBy the end of this chapter, you will be able to:\n\n- Explain the purpose of linear regression as a tool for modeling and prediction\n- Visualize and assess linear relationships between numeric variables using scatterplots\n- Use correlation to evaluate whether variables are appropriate for regression modeling\n- Fit a simple linear regression model using `lm()` and interpret the slope and intercept\n- Interpret key model outputs including coefficients, p-values, R², adjusted R², and the F-statistic\n- Generate predicted values and calculate residuals from a fitted regression model\n- Diagnose model assumptions by visually and statistically evaluating residuals\n- Test for heteroscedasticity using the Breusch–Pagan test\n- Extend simple regression to multiple regression by adding additional predictors\n- Compare competing regression models using adjusted R² and AIC\n- Select a parsimonious model that balances explanatory power and complexity\n\n## Loading Our Data {#sec-linear-reg-data}\n\nWe start by importing the necessary packages, reading in our data from the `reproresearchR` package (@R-reproresearchR), and quickly doing an overview of the data.\n\n\n::: {#tbl-loading-data .cell tbl-cap='Using the skim function provides us with insightsinto our data.'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(reproresearchR)\n\npizza_sales<- pizza_prices\n\nlibrary(skimr)\n\nskim(pizza_sales)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |            |\n|:------------------------|:-----------|\n|Name                     |pizza_sales |\n|Number of rows           |156         |\n|Number of columns        |3           |\n|_______________________  |            |\n|Column type frequency:   |            |\n|numeric                  |3           |\n|________________________ |            |\n|Group variables          |None        |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|     mean|       sd|       p0|      p25|      p50|      p75|      p100|hist  |\n|:-------------|---------:|-------------:|--------:|--------:|--------:|--------:|--------:|--------:|---------:|:-----|\n|Week          |         0|             1|    78.50|    45.18|     1.00|    39.75|    78.50|   117.25|    156.00|▇▇▇▇▇ |\n|Total Volume  |         0|             1| 88023.50| 22863.94| 55031.00| 74347.00| 83889.00| 95113.00| 227177.00|▇▃▁▁▁ |\n|Total Price   |         0|             1|     2.66|     0.13|     2.31|     2.58|     2.67|     2.75|      2.96|▁▃▇▆▂ |\n\n\n:::\n:::\n\n\n## Cleaning Our Data {#sec-linear-reg-cleaning-data}\n\nIn @sec-cleaning-data-correlation we had to clean our data because of the spaces in the column headers. Our current data has the same issue, as \"Total Volume\" and \"Total Price\" both have a space in them. Looks like the `clean_names()` command will come in handy again! \n\nLet's also do some other cleaning while we are at it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(janitor)\n\n# Let's get rid of any spaces in the column names\npizza_sales<- clean_names(pizza_sales)\n\n# We just want to see the relationship between volume and price, so week does not matter\npizza_sales<- pizza_sales |> select(-1)\n\n# Let's rename our column names to make things easier\npizza_sales <- pizza_sales |>\n  rename(price = total_price, volume = total_volume)\n```\n:::\n\n\nWe now have a cleaner dataset we can use!\n\n## Visualizing Relationships {#sec-linear-reg-viz}\n\nAs emphasized in every chapter, it is **imperative** that we first graph our data to see what it looks like before we run any statistical analyses. Visuals really help us understand our data. Is our data linear? Can we see any patterns? *Let's find out!*\n\nFor regression models, we use scatterplots. For a scatterplot, all we need are two numerical variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Now, let us graph our data using ggplot\n# As always with ggplot, we have our data, our aesthetics, and our geometry.\n\npizza_plot <- ggplot(pizza_sales, aes(x = price, y = volume)) +\n  geom_point(size = 3)  +\n  geom_smooth(method = \"lm\", se = FALSE) + # this adds a \"line of best fit\"\n  theme_minimal() +\n  labs(\n    title = \"Analysis of Pizza Sales\",\n    subtitle = \"You know the rule, one bite...\",\n    x = \"Price ($)\", y = \"Volume\"\n  )\n\npizza_plot\n```\n\n::: {.cell-output-display}\n![Scatterplot showing the relationship between pizza price and weekly sales volume, with a fitted linear trend line. The downward slope indicates a negative linear association, suggesting that higher prices are associated with lower sales volume. This visualization is used to assess linearity and motivate the use of correlation and linear regression.](08-Linear-Regression_files/figure-html/fig-scatter-price-volume-1.png){#fig-scatter-price-volume width=672}\n:::\n:::\n\n\nIf we wanted to use another package instead of ggplot, we could also use the library `ggformula` (\\@-Rggformula), whihc has `gf_point()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggformula)\npizza_plot_ggformula <- gf_point(volume ~ price, data = pizza_sales) |> gf_lm(color =\"purple\")\n\npizza_plot_ggformula\n```\n\n::: {.cell-output-display}\n![Scatterplot of pizza price and weekly sales volume created using the ggformula package, with a fitted linear regression line. This plot conveys the same information as the ggplot version, demonstrating that different visualization frameworks can be used to explore linear relationships.](08-Linear-Regression_files/figure-html/fig-scatter-ggformula-1.png){#fig-scatter-ggformula width=672}\n:::\n:::\n\n\nHere is a side by side comparison of what they look like. Very similar indeed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork)\n\npizza_plot + pizza_plot_ggformula\n```\n\n::: {.cell-output-display}\n![Side-by-side comparison of scatterplots generated using ggplot2 and ggformula. Both visualizations display the same negative linear relationship between pizza price and sales volume, illustrating that different plotting systems can yield equivalent analytical insights.](08-Linear-Regression_files/figure-html/fig-patchwork-regression-1.png){#fig-patchwork-regression width=672}\n:::\n:::\n\n\nOur data is already telling us a lot. From both of our graphics, we can see that as price is going up, volume is going down, indicating a negative correlation. Our line also seems pretty straight, indicating what seems to be a moderately strong correlation.\n\n## Understanding Correlation {#sec-cor-linear-reg}\n\nBefore we get to a linear regression, it is best to first understand how (if at all) our variables are correlated with each other. For a review on correlation, go back to @sec-intro-cor of the textbook.\n\nWe are first trying to figure out what variables, if any, should be included in our linear regression model, and this is exactly where correlation comes into play.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(pizza_sales$volume,pizza_sales$price)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  pizza_sales$volume and pizza_sales$price\nt = -10.8, df = 154, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.7375315 -0.5567684\nsample estimates:\n       cor \n-0.6564736 \n```\n\n\n:::\n:::\n\n\nWhen we run a correlation, we are looking for three things:\n\n1.  The direction: is a positive or negative interaction?\n2.  The strength: how close is it to -1, 0, 1?\n3.  The p-value: Is it statistically significant?\n\nThe code above answers all three questions:\n\n1.  The direction: is negative.\n2.  The strength: about −0.66, indicating a moderately strong negative correlation.\n3.  The p-value: \\< 0.05 indicates that the relationship between price and volume is unlikely due to chance.\n\nWith a correlation coefficient of -0.66, we have a moderately strong negative correlation between price and volume. As price goes up, volume goes down - just what we saw in our graphs!\n\n## Linear Regression Model {#sec-linear-reg-model}\n\nWe have identified that there is a significant negative correlation between the two variables. Since we want to be able to predict the amount (volume) of pizza sold using price, our next step is to run a linear regression model.\n\nWith a linear regression model, we are trying to build the line of best fit and figure out the equation for the line.\n\n::: callout-note\n### The formula for a line is:\n\n$$y = mx + b$$ Where:\n\n- *y* is the predicted value (in this case, volume)\n- *m* is the slope\n- *x* is the given value (in this case, price)\n- *b* is the y intercept (the y value when x is 0)\n:::\n\nWhen we are able to get the slope and the intercept, we can then begin to predict values.\n\nTo run a linear regression model, we can use the lm command. It follows the structure:\n\n- lm(y \\~ x, data = dataset)\n- lm(what we want to predict \\~ the predictor, data = our dataset)\n\n\n::: {#tbl-lm .cell tbl-cap='Linear Regression Model Predicting Pizza Sales Volume by Price'}\n\n```{.r .cell-code}\npizza_lm <- lm(volume ~ price, data = pizza_sales)\n# The code above is saving our linear regression model as pizza_lm\n\nsummary(pizza_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = volume ~ price, data = pizza_sales)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-28602 -11685  -1824   8379 110857 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   385442      27575   13.98   <2e-16 ***\nprice        -111669      10340  -10.80   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 17300 on 154 degrees of freedom\nMultiple R-squared:  0.431,\tAdjusted R-squared:  0.4273 \nF-statistic: 116.6 on 1 and 154 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# When we call summary on our model, we can find out our key insights\n```\n:::\n\n\nCongratulations! We have just run our first linear regression model! We have some key insights, including:\n\n- Intercept: *385,442.* This is our **b value** on our line equation. This means that when the price of pizza is 0 (free pizza would be nice, but really just a dream), the y value would be 385442.\n- price: *-111,669.* This is our slope, or our **m** value on our line equation. This tells us that for every one-unit increase in price, sales volume decreased by approximately 111,669 units. This makes sense, since we have a negative correlation.\n- Multiple R-squared: As we have seen before, this tells us how much of the variability our model explains. For our example, about 43% of the variance in pizza sales volume is explained by price alone. **Warning:** Multiple R-squared in linear regression models always increases with each new predictor added to a model, regardless of how potent it is.\n- Adjusted R-squared: This is almost identical to the Multiple R-squared value, except that it takes into account each new predictor added, and does not go up just because a new predictor was added to the model.\n- p-value: There are three p-values here. The first two, on the intercept and price lines, indicate if the relationships are statistically significant, which they are. The bottom one is if the model itself is significant, which it is.\n- F-statistic: This tells us how strong our model is. 116.6 is a high value.\n\n::: callout-note\n### Putting this all together, our line formula is:\n\ny = -111,669x + 385,442\n:::\n\nAll of these insights together mean that this is a very good model to predict volume of pizza sold.\n\nIn R, we always want to explore different packages. The `broom` package (\\@-Rbroom) in R is very helpful when making statistical objects into nicer tibbles, usig the `tidy()` function.\n\n\n::: {#tbl-lm-with-broom-tidy .cell tbl-cap='Using the tidy function from the broom package to see the linear regression output.'}\n\n```{.r .cell-code}\n# If we want to get the same information from our lm model using a different package\n\nlibrary(broom)\ntidy(pizza_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)  385442.    27575.      14.0 3.44e-29\n2 price       -111669.    10340.     -10.8 1.36e-20\n```\n\n\n:::\n:::\n\n\n\n::: {#tbl-lm-with-broom-glance .cell tbl-cap='Using the glance function from the broom package to see the linear regression output.'}\n\n```{.r .cell-code}\nglance(pizza_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared  sigma statistic  p.value    df logLik   AIC   BIC\n      <dbl>         <dbl>  <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.431         0.427 17303.      117. 1.36e-20     1 -1743. 3491. 3501.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n:::\n\n\nOur finalized equation is y (-111,669 \\* price) + 385,442. All we need to do is plug in any price value, and we can predict the volume of pizza sold.\n\n## Checking the residuals {#sec-residual-checking}\n\n::: callout-tip\n### To make sure that our data for the line looks good, it is important to answer the question:\n\nHow close are our predicted values to our actual values?\n:::\n\nTo answer this question, we need to figure out the predicted values and then their *residuals* (the difference between the actual vs the predicted value).\n\nWe can do this in R with the two commands below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npizza_sales <- pizza_sales |>\n  mutate(predicted = predict(pizza_lm),\n         residuals = residuals(pizza_lm))\n```\n:::\n\n\nTo visually see the difference between the actual values and the predicted values, we can create a similar scatterplot as before, but add lines connecting our line of best fit and our points.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# What if we want to see actual vs predicted on our plot?\npizza_plot_residuals <- ggplot(pizza_sales, aes(x = price, y = volume)) +\n  geom_point(size = 3)  +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  geom_segment(aes(xend = price, yend = predicted), color = \"gray\", linewidth = 0.7) +\n  theme_minimal() +\n  labs(\n    title = \"Analysis of Pizza Sales\",\n    subtitle = \"Gray lines show residuals (differences between actual and model predictions)\",\n    x = \"Price ($)\", y = \"Volume\"\n  )\n\npizza_plot_residuals\n```\n\n::: {.cell-output-display}\n![Scatterplot of pizza price and sales volume with residual lines connecting observed values to model predictions. Each gray line represents a residual, illustrating the difference between actual sales and values predicted by the linear regression model.](08-Linear-Regression_files/figure-html/scatterplot-with-residual-lines-1.png){width=672}\n:::\n:::\n\n\nWith our residuals, we want them to be random. Visually, that means that the residual values should be scattered on an x-y plane without a pattern. To see this, we can graph the residuals themselves.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Let us graph our residuals to make sure they are random\nggplot(pizza_sales, aes(x = predicted, y = residuals)) +\n  geom_point(color = \"blue\") +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  geom_smooth(se = FALSE, color = \"red\", linetype = \"dotted\")+\n  labs(\n    title = \"Residuals Plot\",\n    x = \"Predicted Volume\",\n    y = \"Residuals\"\n  )\n```\n\n::: {.cell-output-display}\n![Residuals plotted against predicted sales volume from the linear regression model. Random scatter around the horizontal zero line indicates homoscedasticity, while systematic patterns would suggest violations of regression assumptions.](08-Linear-Regression_files/figure-html/graphing-residuals-1.png){width=672}\n:::\n:::\n\n\nThe red line in the graph above has a slight curve, showing that our model is less accurate at the extremes (low and high prices). Thankfully, this pattern isn’t very pronounced.\n\n::: callout-tip\n### To accompany the visual, we want to statistically test for heteroscedasticity, meaning:\n\nAre the residuals roughly equal in variance across all predicted values?\n:::\n\nWe will either see:\n\n- Homoscedasticity: residuals are equally spread (good)\n- Heteroscedasticity: residuals get wider or narrower as predictions change (bad)\n\nThe Breusch-Pagan test provides insights for this. To perform this in R, we will use the `bptest()` function from the `lmtest` package (\\@-Rlmtest).\n\n\n::: {#tbl-bptest-using-lmtest .cell tbl-cap='Breusch-Pagan output for the linear regression model.'}\n\n```{.r .cell-code}\nlibrary(lmtest)\n\nbptest(pizza_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  pizza_lm\nBP = 7.7392, df = 1, p-value = 0.005403\n```\n\n\n:::\n:::\n\n\nThe main focus point here is the p-value:\n\n- \n\n  > 0.05 Fail to reject H₀ → residuals are homoscedastic (good)\n\n- \\< 0.05 Reject H₀ → residuals are heteroscedastic (not ideal)\n\nSince our p-value is less than .05, our residuals are heteroscedastic.\n\nThis **does not** invalidate our model, and for right now, we do not need to change it. It is just showing us that it is not *perfect*, and not all prices predict equally well. In reality, this might happen if higher-priced pizzas are sold less frequently, giving us fewer data points and more variability.\n\n**Congratulations, we have just completed our first linear regression model!**\n\n## Adding more variables {#sec-more-variables}\n\nThroughout this chapter, we have only looked at 2 variables: *price* and *volume* to see if the former can predict the latter. But, what if we have more variables? Can we also utilize them in our regression model?\n\nLet's find out!\n\nLet us create two new variables to add to our data: one where David Portnoy visited the pizza shop and another on how much was spent on advertising.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Now, let's add some other variables to our data\nset.seed(42)\n\n# 1) Dave Portnoy visit.\npizza_sales <- pizza_sales |>\n  mutate(portnoy_visit = rbinom(n(), size = 1, prob = 0.06))  # about 3–6% of weeks\n\n# 2) Ad spend\npizza_sales <- pizza_sales |>\n  mutate(ad_spend = round(runif(n(), 800, 6000), 0))\n```\n:::\n\n\nNow, since we have multiple variables, we can run what's called multivariate regression model. To add more predictors, we simply use the + sign in our lm command after our first predictor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(volume ~ price, data = pizza_sales)                      # baseline\n\nm2 <- lm(volume ~ price + portnoy_visit, data = pizza_sales)      # add portnoy visit\n\nm3 <- lm(volume ~ price + ad_spend, data = pizza_sales)           # add ad spending\n\nm4 <- lm(volume ~ price + ad_spend + portnoy_visit, data = pizza_sales)  # both\n```\n:::\n\n\nBoom! In the code above, we have now run 4 regression models, with every combination included.\n\nNow, we can run the summary or glance command on each model individually, compare the models manually, but that would require a lot of working memory power on our end. *Or* we could utilize some commands in R to make our lives much easier.\n\n\n::: {#tbl-aic .cell tbl-cap='A table of all of the AIC values for each of the linear regression models.'}\n\n```{.r .cell-code}\n# How do we know which model is the best?\n\nAIC(m1, m2, m3, m4) |> arrange(AIC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   df      AIC\nm2  4 3486.244\nm4  5 3488.239\nm1  3 3491.395\nm3  4 3493.327\n```\n\n\n:::\n\n```{.r .cell-code}\n# This code provides us with an AIC (Akaike Information Criterion) value.\n# The smaller the AIC, the better the model’s trade-off between complexity and fit.\n```\n:::\n\n\n\n::: {#tbl-aic-map .cell tbl-cap='Comparison of Model Fit Indices across Four Linear Regression Models.'}\n\n```{.r .cell-code}\n# Let's say we want to use the broom function again to do a model comparison\nmodels <- list(m1, m2, m3, m4)\n# In the code above, we are taking all of our models and putting them into a \"list\" of models\n\nnames(models) <- c(\"m1\",\"m2\",\"m3\",\"m4\")\n# In the code above, we are just giving each item in the list a name\n\n# In the code below, we are saying \"Hey, run glance on every single item on the models list and create a data frame\n\nmap_df(models, ~glance(.x), .id = \"model\") |> select(model, r.squared,adj.r.squared,p.value,AIC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  model r.squared adj.r.squared  p.value   AIC\n  <chr>     <dbl>         <dbl>    <dbl> <dbl>\n1 m1        0.431         0.427 1.36e-20 3491.\n2 m2        0.456         0.449 5.57e-21 3486.\n3 m3        0.431         0.424 1.79e-19 3493.\n4 m4        0.456         0.446 5.07e-20 3488.\n```\n\n\n:::\n:::\n\n\nWith both of these, we now have:\n\n1.  R²: A higher R squared means the model is a better predictor. *Remember, R\\^2 always goes up with each added predictor, no matter how salient they actually are.*\n2.  Adjusted R²: A higher adjusted R squared means the model is a better predictor. *Adjusted R² always takes into account the number of predictors and does not inherently increase with more predictors.*\n3.  p-value: If these models are statistically significant.\n4.  AIC: tells us how good our models are. A lower number means a better model.\n\nOverall, the goal is to create the most **parsimonious** regression model as possible. That is, the model with the fewest necessary predictors. As such, the model that is most parsimonious is m1, the model with just price. Yes, other models have higher adjusted R\\^2 values and lower AIC numbers, but only *slightly.* In this case, m1 is the model to go with.\n\n### Bonus code {#sec-linear-reg-bonus-code}\n\nIf you are looking to compare multiple regression models in a faster way, you could also utilize the code below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfull_model <- lm(volume ~ price + ad_spend + portnoy_visit, data = pizza_sales)\n\nstep_model <- step(full_model, direction = \"both\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=3043.53\nvolume ~ price + ad_spend + portnoy_visit\n\n                Df  Sum of Sq        RSS    AIC\n- ad_spend       1 1.4575e+06 4.4042e+10 3041.5\n<none>                        4.4041e+10 3043.5\n- portnoy_visit  1 2.0473e+09 4.6088e+10 3048.6\n- price          1 3.1199e+10 7.5240e+10 3125.1\n\nStep:  AIC=3041.54\nvolume ~ price + portnoy_visit\n\n                Df  Sum of Sq        RSS    AIC\n<none>                        4.4042e+10 3041.5\n+ ad_spend       1 1.4575e+06 4.4041e+10 3043.5\n- portnoy_visit  1 2.0659e+09 4.6108e+10 3046.7\n- price          1 3.1252e+10 7.5294e+10 3123.2\n```\n\n\n:::\n:::\n\n\n## Conclusion {#sec-linear-reg-conclusion}\n\nCongratulations! You have successfully run correlations (to help see what variables we want to build our regression model with), regression models, multiple regression models, compared models, and even analyzed the differences between our actual values and our predicted values.\n\nDon't underestimate how powerful regression models can be. With a line equation, you can help predict any variable!\n\n## Key Takeaways {#sec-linear-reg-takeaways}\n\n- Linear regression helps us predict one variable (Y) from another (X) using a line of best fit.\n- The equation of the line is y = mx + b, where:\n  - m = slope (how much Y changes for every 1-unit change in X)\n  - b = intercept (the value of Y when X = 0)\n- The slope tells us both the direction and strength of the relationship.\n- Residuals = actual - predicted values; smaller residuals = better model fit.\n- A good model has random, evenly scattered residuals (homoscedasticity).\n- R² tells us how much variance in Y is explained by X.\n- Adjusted R² penalizes unnecessary predictors in multiple regression models.\n- AIC helps compare models: lower AIC = better balance between fit and simplicity.\n- Parsimonious models (simpler ones that still explain the data well) are preferred.\n- Stepwise regression automatically selects the most parsimonious model using AIC.\n- Correlation shows association; regression goes further by predicting and quantifying impact.\n- Always visualize both your model fit and your residuals before interpreting results!\n\n## Checklist {#sec-linear-reg-checklist}\n\n*When running linear regressions, have you:*\n\n- [ ] Loaded and inspected your data (skim, summary, str)\n- [ ] Cleaned and renamed your variables as needed\n- [ ] Graphed your variables with scatterplots and trend lines\n- [ ] Checked that the relationship looks linear\n- [ ] Calculated correlations before fitting your model\n- [ ] Built your model using lm(y \\~ x)\n- [ ] Examined coefficients (intercept and slope) and their significance\n- [ ] Computed predicted values and residuals\n- [ ] Graphed residuals to ensure randomness (no U-shape or funnel)\n- [ ] Tested for homoscedasticity using bptest() (Breusch–Pagan test)\n- [ ] (Optional) Checked residual normality with a histogram or QQ plot\n- [ ] Interpreted R² and Adjusted R² to describe model performance\n- [ ] Added additional predictors for multiple regression if needed\n- [ ] Compared models using AIC or stepwise regression\n- [ ] Selected the most parsimonious model (best fit with the least complexity)\n- [ ] Clearly interpreted what the slope and intercept mean in real-world terms\n- [ ] Reported results visually (scatterplot, line of best fit, residual plot)\n\n## Key Functions & Commands {#sec-linear-reg-key-functions}\n\nThe following functions and commands are introduced or reinforced in this chapter to support linear regression modeling, diagnostics, and model selection.\n\n- `lm()` *(stats)*\n  - Fits linear and multiple linear regression models using a formula interface.\n- `summary()` *(base R)*\n  - Summarizes regression model results, including coefficients, R², F-statistic, and p-values.\n- `cor.test()` *(stats)*\n  - Computes and tests correlations to assess whether predictors are suitable for regression.\n- `predict()` *(stats)*\n  - Generates predicted values from a fitted regression model.\n- `residuals()` *(stats)*\n  - Extracts residuals (actual − predicted values) from a regression model.\n- `tidy()` *(broom)*\n  - Converts regression coefficients into a clean, tidy data frame.\n- `glance()` *(broom)*\n  - Extracts model-level statistics (e.g., R², adjusted R², AIC) into a single-row summary.\n- `bptest()` *(lmtest)*\n  - Performs the Breusch–Pagan test to assess heteroscedasticity of residuals.\n- `AIC()` *(stats)*\n  - Compares regression models using Akaike Information Criterion to balance fit and complexity.\n- `step()` *(stats)*\n  - Performs stepwise model selection to identify a parsimonious regression model.\n\n## Example APA-style Write-up {#sec-linear-reg-apa}\n\nThe following example demonstrates one acceptable way to report the results of a simple linear regression in APA style.\n\n**Simple Linear Regression**\n\nA simple linear regression was conducted to examine whether pizza price predicted weekly pizza sales volume. The overall regression model was statistically significant, $F(1, 148) = 116.60, p < .001$, and explained approximately 43% of the variance in pizza sales volume ($R^2 = .43$).\n\nPizza price was a significant negative predictor of sales volume, $b = -111,669$, $SE = 10,347$, $t = -10.80$, $p < .001$, indicating that higher pizza prices were associated with lower weekly sales volume. Specifically, for each one-unit increase in pizza price, weekly pizza sales decreased by approximately 111,669 units.\n\n## 💡 *Reproducibility Tip:* {#sec-linear-reg-tip}\n\nLinear regression models involve many analytic choices, including which variables to include, how to assess relationships, and how to evaluate model fit. To support reproducibility, make each of these decisions explicit and evidence-based.\n\nBefore fitting a model, visualize relationships and examine correlations to justify why predictors are included. After fitting the model, report diagnostics—such as residual plots and measures of fit—to demonstrate that assumptions were checked.\n\n::: callout-warning\n### Remember:\n\n*Adding more variables does not always lead to a better model*.\n:::\n\nRegression results are only reproducible when both the code *and the reasoning behind the model* are transparent.\n",
    "supporting": [
      "08-Linear-Regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}