{
  "hash": "f7bc9e45a9d85424f8454484f5d6d213",
  "result": {
    "engine": "knitr",
    "markdown": "# Logistic Regression {#sec-log-reg}\n\n## Introduction {#sec-intro-log-reg}\n\nTwo chapters ago, we did a great job of creating linear regression models, which was the first time in this book that we created prediction models. With a lot of TLC, we created a y = mx + b (rhymed on purpose) so that whatever future of value of x we had, we could predict what y would be.\n\nHowever, that was when we had numeric data. What happens when we do not have any numeric data? From our last chapter, we know that is where a chi-square comes in, but what if we want to still do some predicting? This is exactly where **Logistic Regression** comes into play.\n\n::: callout-note\n### The question we are trying to answer is:\n\nCan we predict if someone will default on their credit cards based on other factors about them?\n:::\n\nCould you have predicted that there would be another chapter about making predictions...?\n\nUsing the `ISLR2` package, we will be working with the `Default` dataset.\n\n## Learning Objectives {#sec-log-reg-objectives}\n\nBy the end of this chapter, you will be able to:\n\n- Explain when logistic regression is appropriate and how it differs from linear regression\n- Interpret probabilities, odds, log-odds, and odds ratios in the context of binary outcomes\n- Perform exploratory data analysis for a binary response variable, including calculating proportions and odds\n- Visualize relationships between a binary outcome and predictor variables\n- Split data into training and testing sets for predictive modeling\n- Fit a logistic regression model using `glm()` with a binomial family\n- Interpret logistic regression coefficients and convert them to odds ratios using `exp()`\n- Assess model fit using McFadden’s pseudo-R²\n- Evaluate predictor importance and check for multicollinearity using VIF\n- Generate predicted probabilities and classifications from a fitted model\n- Evaluate classification performance using confusion matrices, sensitivity, specificity, and balanced accuracy\n- Assess model discrimination using ROC curves and the Area Under the Curve (AUC)\n\n## Load and Preview Data {#sec-log-reg-data}\n\nFirst, we need to load the `ISLR2` (@R-ISLR2) package and then we will create our `cc_data` dataset using the `Default` dataset, which inside the package.\n\n\n::: {#tbl-loading-data-ISLR2 .cell tbl-cap='The skim function provides us with insightsinto our data that are helpful when first looking at the data.'}\n\n```{.r .cell-code}\nlibrary(ISLR2)\nlibrary(tidyverse)\n\ncc_data <- Default # this data comes from the ISLR2 package\n\nlibrary(skimr)\n\nskim(cc_data)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |        |\n|:------------------------|:-------|\n|Name                     |cc_data |\n|Number of rows           |10000   |\n|Number of columns        |4       |\n|_______________________  |        |\n|Column type frequency:   |        |\n|factor                   |2       |\n|numeric                  |2       |\n|________________________ |        |\n|Group variables          |None    |\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts          |\n|:-------------|---------:|-------------:|:-------|--------:|:-------------------|\n|default       |         0|             1|FALSE   |        2|No: 9667, Yes: 333  |\n|student       |         0|             1|FALSE   |        2|No: 7056, Yes: 2944 |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|     mean|       sd|     p0|      p25|      p50|      p75|     p100|hist  |\n|:-------------|---------:|-------------:|--------:|--------:|------:|--------:|--------:|--------:|--------:|:-----|\n|balance       |         0|             1|   835.37|   483.71|   0.00|   481.73|   823.64|  1166.31|  2654.32|▆▇▅▁▁ |\n|income        |         0|             1| 33516.98| 13336.64| 771.97| 21340.46| 34552.64| 43807.73| 73554.23|▂▇▇▅▁ |\n\n\n:::\n:::\n\n\nOur data contains 10,000 rows of data, each relating to a particular person. Two variables are **factors**, the other two are **numeric.** The variables are:\n\n1.  default: A factor with levels No and Yes indicating whether the customer defaulted on their debt\n2.  student: A factor with levels No and Yes indicating whether the customer is a student\n3.  balance: The average balance that the customer has remaining on their credit card after making their monthly payment\n4.  income: Income of customer\n\n::: callout-note\n### Regarding the ISLR2 package:\n\n*The definitions of the columns come directly from the description found in the package*\n:::\n\nWe have our most crucial data point - if the person did or did not default on their credit card payments. Soon, we will be using the other data points to see if we can predict if someone will or will not default on their payments.\n\nFirst, let's do a little digging to find out more about our data.\n\n## Exploratory Data Analysis {#sec-log-reg-exploration}\n\nBefore we predict if a person defaults or not, it is good to find out more about the default variable, answering some questions like:\n\n- How many people have defaulted?\n- What **percentage** of people have defaulted?\n- What are the **odds** that someone will default?\n- What are the preliminary relationships between default and the other variables?\n\n\n::: {#tbl-proportion-odds .cell}\n\n```{.r .cell-code}\ntable(cc_data$default)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  No  Yes \n9667  333 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Proportion of people who default\np <- mean(cc_data$default == \"Yes\")\np*100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.33\n```\n\n\n:::\n\n```{.r .cell-code}\nodds <- p / (1 - p)\n\n# Below provides us with the default rate\ncat(\"Default rate:\", round(p*100,2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDefault rate: 3.33 %\n```\n\n\n:::\n\n```{.r .cell-code}\n# Below provides us with the odds of someone defaulting\ncat(\"Odds of defaulting:\", round(odds,4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOdds of defaulting: 0.0344 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Below provides us with the odds ratio\ncat(\"Equivalent odds ratio (1 in every\", round(1/odds,0), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEquivalent odds ratio (1 in every 29 )\n```\n\n\n:::\n\n```{.r .cell-code}\n# Cross-tab between student status and default\ncc_data |> count(default, student) |> arrange(desc(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  default student    n\n1      No      No 6850\n2      No     Yes 2817\n3     Yes      No  206\n4     Yes     Yes  127\n```\n\n\n:::\n:::\n\n\n\n::: {#tbl-favstats-income-default .cell tbl-cap='A summarized table uncovering insights into the relationship between income and default.'}\n\n```{.r .cell-code}\n# Quick descriptive stats\nlibrary(mosaic)\n\nfavstats(income ~ default, data = cc_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  default       min       Q1   median       Q3      max     mean       sd    n\n1      No  771.9677 21405.06 34589.49 43823.76 73554.23 33566.17 13318.25 9667\n2     Yes 9663.7882 19027.51 31515.34 43067.33 66466.46 32089.15 13804.22  333\n  missing\n1       0\n2       0\n```\n\n\n:::\n:::\n\n\n\n::: {#tbl-favstats-balance-default .cell tbl-cap='A summarized table uncovering insights into the relationship between balance and default.'}\n\n```{.r .cell-code}\nfavstats(balance ~ default, data = cc_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  default      min        Q1    median       Q3      max      mean       sd\n1      No   0.0000  465.7146  802.8571 1128.249 2391.008  803.9438 456.4762\n2     Yes 652.3971 1511.6110 1789.0934 1988.870 2654.323 1747.8217 341.2668\n     n missing\n1 9667       0\n2  333       0\n```\n\n\n:::\n:::\n\n\nSome things that were uncovered in the code above:\n\n- The probability of someone defaulting is 0.0333.\n- The percentage of people defaulting is 3.33%.\n- **Note**: Probabilities are always going to be a number between 0 and 1. This is incredibly important later when we are trying to create our line.\n- 1 in every 29 people will default on their credit card. These are the **odds,** which by definition, compare successes (defaults) to failures (non-defaults).\n- While probabilities are between 0 and 1, odds are between 0 and ∞.\n- An overwhelming majority of students did not default.\n- The mean income of people who do not default is only slightly higher than people who do.\n- The mean balance of people who **do** default is more than *double* the amount than people who **don't**.\n\nOverall, most people don't default on their credit cards, and while we see differences in means, we do not know if the difference is statistically significant or not.\n\nNow that we have some insights, it is time to visualize!\n\n## Visualize Relationships {#sec-log-reg-viz}\n\nWe are going to make three different visualizations:\n\n1.  A bar plot of defaults\n2.  A histogram of balances split by default, and then\n3.  A scatterplot of balance and income\n\nFor fun, we will be utilizing some themes from the `ggthemes` package. When recreating these on your own, of course feel free to play around and change the themes. As I always say, R puts the r in Artist!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggthemes)\n\n# Default distribution\nggplot(cc_data, aes(x = default, fill = default)) +\n  geom_bar() +\n  labs(title = \"Count of Defaulters vs Non-Defaulters\", y = \"Count\", x = \"Default?\") +\n  theme_economist()\n```\n\n::: {.cell-output-display}\n![Most customers do not default on their credit cards, with defaulters representing only about 3% of the dataset.](09-Logistic-Regression_files/figure-html/fig-default-bargraph-1.png){#fig-default-bargraph width=672}\n:::\n:::\n\n\nFor a quick review on histograms, see @sec-ggplot-histogram.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Balance by default\nggplot(cc_data, aes(x = balance, fill = default)) +\n  geom_histogram(position = \"identity\", alpha = 0.6, bins = 30) +\n  labs(title = \"Higher Balances Increase Likelihood of Default\",\n       x = \"Average Credit Card Balance ($)\", y = \"Count\") +\n  theme_economist_white()\n```\n\n::: {.cell-output-display}\n![While most customers do not default on their credit cards, it seems that people that do have higher balances.](09-Logistic-Regression_files/figure-html/fig-default-histogram-1.png){#fig-default-histogram width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Balance vs. Income\nggplot(cc_data, aes(x = balance, y = income, color = default)) +\n  geom_point(alpha = 0.6) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"black\", linetype = \"dashed\") +\n  labs(title = \"Customers Who Default Tend to Have Higher Balances\",\n       subtitle = \"Each point represents a customer\",\n       x = \"Average Credit Card Balance ($)\",\n       y = \"Annual Income ($)\",\n       color = \"Default\") +\n  theme_minimal(base_size = 13) +\n  theme(plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![Regardless of if you default or not, there is a negative relationship between Annual Income and Average Credit Card Balance.](09-Logistic-Regression_files/figure-html/fig-default-scatter-1.png){#fig-default-scatter width=672}\n:::\n:::\n\n\nThe visualizations look great! In terms of insights, we see (again) that most people do not default on their credit cards, most balances are around the 800 range for non-defaulters and higher for the defaulters, and that as balance increases, income decreases.\n\nWith a basic understanding of our data, it is now time to do something really fun - split our data!\n\n## Train and Test Split {#sec-log-reg-splitting-data}\n\nRight now, we have one complete data set. What is amazing about our data is that it is complete. We have 10,000 data points each with the crucial information of if the person did or did not default. Our goal is still to create a model that takes the information we have about the people (if they're a student, their balance, and their income) and use it to predict if a person will or will not default.\n\nIdeally, we want this model to be able to predict it for people in the future? When we build it, **how** will we know how accurate it is?\n\nIn scenarios like this, we can actually split our data into two sets: one for training (creating our model) and one for testing (see how well our model actually works). This is important because we get to test our model using **real** data. It is kind of like practicing a basketball move before you use it in a real game.\n\nOur goal: use a decent portion of our real data to test our model, and compare it to data not used in the model. To help with this, we will be using the `sample.split()` function from the `caTools` pakage (@R-caTools).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# set.seed allows us to get the same split of the data each time we run this code\nset.seed(42)\n\nlibrary(caTools) # Package that helps us split our data into Train and Test sets.\n\n# We are going to be doing a 70/30 split. It is good practice to have most of your data in the training\nsample <- sample.split(cc_data$default, SplitRatio = 0.7)\n\n# This creates our test data, what we will use to train our logistic regression model\ntraining_data <- subset(cc_data, sample == TRUE)\n\n# This creates our test data, what we will measure our model against\n\ntest_data <- subset(cc_data, sample == FALSE)\n```\n:::\n\n\nWe have successfully split our data into a training and a testing set! Again, most of our data is going to go into the training data set. We want our model to be as successful as possible while also providing enough of a chance to see if it works.\n\nWe have our training set, so let's get predicting!\n\n## Build Logistic Regression Model {#sec-log-reg-model}\n\nWhen building a logistic regression model, it is going to look very similar to the linear regression model we built starting in @sec-linear-reg-model. The major difference from a coding perspective between a linear regression and a logistic regression model is that instead of using `lm()`, you need to use `glm()`.\n\nBefore we create our model, let's take a step back. Logistic regression, just like linear regression, is a tool to help us predict an outcome. Specifically, we are predicting the **probability** of an outcome.\n\n::: callout-note\n### The formula for the logistic regression is as follows:\n\n$$\\log\\left(\\frac{p}{1 - p}\\right) = \\beta\\_0 + \\beta\\_1 \\cdot \\text{balance} + \\beta\\_2 \\cdot \\text{income} + \\beta\\_3 \\cdot \\text{student}$$\n:::\n\nwhere (p) is the probability of default. The left-hand side is called the *logit*, or log-odds. Notice that the right-hand side looks just like a straight-line regression.\n\nIn Linear Regression, your line goes on forever in both directions. But in probability, you can't be less than 0% or more than 100%. If you used a straight line to predict defaults, the math might eventually say someone has a -20% chance of defaulting, which is impossible.\n\nTo fix this, we use the Sigmoid Function. This \"squashes\" the straight line into an S-curve that stays strictly between 0 and 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(cc_data, aes(x = balance, y = as.numeric(default) - 1)) +\n  geom_point(alpha = 0.2) +\n  geom_smooth(method = \"glm\", method.args = list(family = \"binomial\"), se = FALSE, color = \"red\") +\n  labs(y = \"Probability of Default\", x = \"Balance\")\n```\n\n::: {.cell-output-display}\n![When plotting the balance and the default, the scatterplot creates a line that is not linear, but in fact an S shape.](09-Logistic-Regression_files/figure-html/fig-s-curve-1.png){#fig-s-curve width=672}\n:::\n:::\n\n\nIn @fig-s-curve, notice how the red line transitions from a low probability to a high probability as the balance increases. Unlike a straight linear line, this S-curve naturally 'levels off' at 0 and 1, ensuring our predictions remain realistic probabilities.\n\nNow, let’s get to business and create our logistic regression model.\n\n\n::: {#tbl-creating-model .cell tbl-cap='Logistic Regression Model Predicting the Probability of Credit Default based on Student Status, Account Balance, and Income.'}\n\n```{.r .cell-code}\n# We are using binomial as family since default is yes/no\n\ntrain_model <- glm(default ~ student + balance + income,\n                   family = \"binomial\", data = training_data) \n\nsummary(train_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = default ~ student + balance + income, family = \"binomial\", \n    data = training_data)\n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -1.090e+01  5.931e-01 -18.372  < 2e-16 ***\nstudentYes  -8.245e-01  2.835e-01  -2.908  0.00364 ** \nbalance      5.796e-03  2.805e-04  20.661  < 2e-16 ***\nincome       2.768e-06  9.736e-06   0.284  0.77614    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 2043.8  on 6999  degrees of freedom\nResidual deviance: 1098.2  on 6996  degrees of freedom\nAIC: 1106.2\n\nNumber of Fisher Scoring iterations: 8\n```\n\n\n:::\n:::\n\n\nAfter we create our model and call `summary()`, we get an output that should look similar to the outputs we've seen before in this chapter. Taking a look at our wall of words, it is incredibly important to note that the numbers here represent the log-odds\n\nModel interpretation:\n\n1.  Student (negative coefficient, not significant): Students less likely to default.\n2.  Balance (positive, significant): Higher balance = higher odds of default.\n3.  Income (tiny effect, not significant).\n4.  “Fisher Scoring iterations: 8” means R needed 8 rounds to find best fit.\n\nOne thing to note is that unlike a linear regression model, logistic regression models take a few tries to create the best model (in this case, 8).\n\nWhile the outputs **look** the same, there is a major difference in the numbers that are output in a logistic regression vs a linear regression. Remember earlier when we calculated the probability of someone defaulting? It was mentioned that probabilities will **always** be a number between 0 and 1. But, when we are creating a *line* in a regression model, we can get any numbers between -∞ and ∞. How does logistic regression, which uses probabilities, make a line then?\n\nLog-odds!\n\nWe need to get a number that actually has a range, and this is exactly where log-odds come in. Because with regression, we need to get a line (and to build a line, we need a formula). Instead of modeling probability, we model the log of the odds. Here is the step by step of how logistic regression works:\n\n1.  Start with a probability.\n2.  Convert to odds.\n3.  Takes the log of the odds\n4.  Using those log odds, fits a regression line\n5.  Converts it back with a logistic function\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert log-odds → odds ratios\nexp(coef(train_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n (Intercept)   studentYes      balance       income \n1.850225e-05 4.384379e-01 1.005813e+00 1.000003e+00 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Example: students have 0.43× the odds (≈57% lower odds) of defaulting\n```\n:::\n\n\nA very important thing to note is that **odds and probability are not the same thing.** With odds ratios, we are looking to see how much larger or smaller it is than 1.\n\n- OR = 1 → no change\n- OR \\> 1 → increase\n- OR \\< 1 → decrease\n\nBreaking this down using our model:\n\n1.  If you are a student, the odds of you defaulting decrease, as the odds ratio is 0.438. Their odds are 56.2% **lower** than non-students (1 - 0.438). This is a significant difference.\n2.  For every dollar your balance increases, the odds of you defaulting increase by 0.58%. This seems small per dollar, but compounds rapidly across real-life balance amounts. For example, increasing the balance by \\$100 multiplies the odds of default by about 1.78, which is a 78% increase in odds.\n3.  The odds ratio for income is so small (OR = 1.000003), that a \\$1 increase in income has basically no influence on your default odds.\n\n### McFadden's Pseudo-R² {#sec-mcfaddens-r-2}\n\nUnlike in linear regression, logistic regression does not have an R²: (for a review on R²: see @sec-linear-reg-model). However, we can use the `pR2()` function from the `pscl` library (@R-pscl) to calculate a pseudo R² value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# McFadden’s pseudo-R2\nlibrary(pscl)\n\npR2(train_model)[\"McFadden\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfitting null model for pseudo-r2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n McFadden \n0.4626515 \n```\n\n\n:::\n:::\n\n\nAs of right now, this is a moderately strong model!\n\n### Variable Importance {#sec-var-importance}\n\nWith the `varImp()` function inside the `caret` package (@R-caret), we can also see which variables are the most important in our regression model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Variable importance\nlibrary(caret)\n\nvarImp(train_model) |> arrange(desc(Overall))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Overall\nbalance    20.6607703\nstudentYes  2.9080015\nincome      0.2843578\n```\n\n\n:::\n\n```{.r .cell-code}\n# balance seems to be the most impactful in our model\n```\n:::\n\n\n### Multicollinearity check {#sec-multicollinearity-check}\n\nJust like in @sec-partial-cor, we want to check to see if there is any interactions between some of our variables that may be impacting our regression model. Using the `vif()` function from the `car` library (@R-car), we can see the interactions between our variables in our model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Multicollinearity check\nlibrary(car)\n\nvif(train_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n student  balance   income \n2.671007 1.072618 2.593366 \n```\n\n\n:::\n\n```{.r .cell-code}\n# does not seem to be any multicollinearity\n# anything less than 5 means no multicollinearity\n```\n:::\n\n\nAs of right now, it is safe to say that there is no multicollinearity, as all values are less than 5.\n\n## Make Predictions {#sec-log-reg-pred}\n\nBefore, we took our data and split it into a training set and a test set. Using the training set, we built a logistic regression model. Now that we have it, it is time to test it against our test data!\n\nAs previously stated, it is best to test our model against real data, because we then get to compare and contrast what our model predicted vs what actually happened. It is now time to do exactly that!\n\nWe are going to create two new columns in our test data:\n\n1.  pred_prob: Our model is going to predict the likelihood of someone defaulting, using that row's data.\n2.  pred_class: based on the probability from pred_prob, it is going to either be \"Yes\" or \"No.\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_data$pred_prob <- predict(train_model, newdata = test_data, type = \"response\")\n\ntest_data$pred_class <- ifelse(test_data$pred_prob > 0.5, \"Yes\", \"No\") |> as.factor()\n```\n:::\n\n\nIn the above code, we used 0.5 as our cutoff for deciding if a person defaulted or not. 0.5 is a good measure since it is at the halfway point, but it is up to you to decide what the marker should be.\n\nWith this code complete, our model has now churned out the results (if someone will or will not default on their credit card).\n\n## Evaluate Model {#sec-log-reg-eval}\n\nUsing real data (our test data) and a built logistic regression model, we now have predicted if a person will or will not default on their credit card. The next question is: **how well did our model predict if someone defaulted on their credit card or not?**\n\nTo do this, we run the command `confusionMatrix`. This comes from the `caret` package which we have already loaded.\n\n\n::: {#tbl-confusion-matrix .cell tbl-cap='Confusion Matrix Evaluating Model Predictions Against Actual Default Status on the Test Dataset.'}\n\n```{.r .cell-code}\nconf_matrix <- confusionMatrix(test_data$pred_class, test_data$default, positive = \"Yes\")\n\nconf_matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction   No  Yes\n       No  2886   71\n       Yes   14   29\n                                          \n               Accuracy : 0.9717          \n                 95% CI : (0.9651, 0.9773)\n    No Information Rate : 0.9667          \n    P-Value [Acc > NIR] : 0.06743         \n                                          \n                  Kappa : 0.3934          \n                                          \n Mcnemar's Test P-Value : 1.247e-09       \n                                          \n            Sensitivity : 0.290000        \n            Specificity : 0.995172        \n         Pos Pred Value : 0.674419        \n         Neg Pred Value : 0.975989        \n             Prevalence : 0.033333        \n         Detection Rate : 0.009667        \n   Detection Prevalence : 0.014333        \n      Balanced Accuracy : 0.642586        \n                                          \n       'Positive' Class : Yes             \n                                          \n```\n\n\n:::\n:::\n\n\nAnother wall of data. The first thing we see if a table of Reference vs Prediction. This tells us our true/false negatives/positives. For instance, there were 14 false positives. Most of our data is accurate: 2886 true negatives (most of our data is negative - people do not default).\n\nNext, we get some performance metrics. Here is an initial breakdown of what we see:\n\n- Accuracy ≈ how often model is correct overall.\n  - The model is very accurate, at about 97%.\n- 95% CI: Where the accuracy of our model most likely lies.\n- No Information Rate (NIR): If we just predicted \"No\" for each row, how accurate would we be.\n  - This is not much different from the actual accuracy.\n- P-value \\[Acc \\> NIR\\]: Is our model statistically different than if we just put \"No\" for each.\n  - The p-value is not statistically significant, meaning there is no difference between running our model or just predicting \"No\" for each person.\n- Sensitivity: how well it finds actual defaults.\n  - Only 29% of actual defaulters are detected.\n- Specificity: how well it identifies non-defaulters.\n  - It predicts non-defaulters at almost 100%.\n- High accuracy but low sensitivity means the model misses many rare defaults.\n- Balanced Accuracy is a better metric for imbalanced data.\n\n## ROC Curve + AUC {#sec-log-reg-roc}\n\nAs always, we want to visualize our data. To do this, we can create a special visualization, an *ROC CURVE,* utilizing the `pROC` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pROC)\n\nroc_obj <- roc(test_data$default, test_data$pred_prob, levels = c(\"No\", \"Yes\"))\nplot(roc_obj, col = \"darkblue\", lwd = 2,\n     main = \"ROC Curve – Logistic Regression\")\n```\n\n::: {.cell-output-display}\n![Receiver Operating Characteristic (ROC) curve for the logistic regression model predicting credit card default. The curve plots sensitivity against 1 − specificity across all possible classification thresholds. Curves closer to the top-left corner indicate better classification performance. The area under the curve (AUC) summarizes the model’s ability to distinguish between defaulters and non-defaulters.](09-Logistic-Regression_files/figure-html/pROC-plot-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nauc(roc_obj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArea under the curve: 0.9529\n```\n\n\n:::\n:::\n\n\nInterpretation:\n\n- ROC curve shows sensitivity vs. 1 - specificity.\n- AUC = 0.95 → excellent ability to distinguish defaulters from non-defaulters.\n- Random guessing = 0.5; perfect model = 1.0\n\n## Interpretation {#sec-log-reg-interpretation}\n\nOur logistic regression model predicts the probability that a person will default on their credit card based on balance, income, and student status.\n\nCoefficients:\n\n- The model found a significant positive relationship between balance and default.\n  - As balance increases, the odds of default rise sharply.\n  - The student variable had a negative coefficient, meaning students are less likely\n  - to default than non-students (about 57% lower odds, holding other factors constant).\n- Income showed a very small, non-significant effect once balance was included.\n\nModel Fit:\n\n- McFadden’s R² ≈ 0.46, suggesting the model explains a moderate amount of variation.\n- The AUC = 0.95, indicating excellent ability to distinguish between defaulters and non-defaulters.\n- Confusion Matrix: high overall accuracy (\\~97%), but this is inflated due to the low number of defaults (class imbalance).\n- The model is excellent at identifying people who will *not* default, but less effective at catching rare defaults.\n\nIn short:\n\n- Balance is the strongest predictor.\n- Students are less likely to default.\n- Income doesn’t matter much here.\n- The model performs very well overall.\n\n## Key Takeaways {#sec-log-reg-takeaways}\n\n- Logistic Regression predicts the *probability* of a categorical (binary) outcome.\n- Instead of fitting a straight line, it models the **log-odds** of the outcome.\n- Coefficients tell us how each variable changes the *log-odds* of the event.\n- Positive coefficients increase the odds; negative ones decrease them.\n- We exponentiate coefficients (exp()) to interpret them as **odds ratios**.\n- Example: An odds ratio of 1.50 means 50% higher odds of the outcome.\n- AUC (Area Under the Curve) tells how well the model separates the two groups:\n  - 0.5 = no skill, 0.7–0.8 = good, 0.8–0.9 = great, \\>0.9 = excellent.\n- Accuracy can be misleading when classes are imbalanced — check sensitivity and specificity instead.\n- ROC curves and confusion matrices help visualize model performance.\n- Logistic regression is a gateway to machine learning — it’s the foundation for classification models in predictive analytics.\n\n## Checklist {#sec-log-reg-checklist}\n\n**When running a logistic regression, have you:**\n\n- [ ] Identified your outcome variable as binary (two categories only)?\n- [ ] Verified your predictors are correctly coded (numeric or factor as needed)?\n- [ ] Explored the data first (EDA, visualizations, proportions, odds)?\n- [ ] Split your data into training and testing sets?\n- [ ] Fit your model using glm(..., family = \"binomial\")?\n- [ ] Checked model summary for significant predictors?\n- [ ] Converted coefficients to odds ratios using exp()?\n- [ ] Checked for multicollinearity using VIF (\\< 5 recommended)?\n- [ ] Calculated a Pseudo-R² (e.g., McFadden’s R²) to assess model fit?\n- [ ] Generated predicted probabilities (type = \"response\") for the test set?\n- [ ] Chosen a classification threshold (e.g., 0.5) and created predicted classes?\n- [ ] Used a confusion matrix to evaluate accuracy, sensitivity, specificity?\n- [ ] Created an ROC curve and reported the AUC value?\n- [ ] Written a clear interpretation that answers your original research question?\n\n## Key Functions & Commands {#sec-log-reg-key-functions}\n\nThe following functions and commands are introduced or reinforced in this chapter to support logistic regression modeling, classification, and model evaluation.\n\n- `glm()` *(stats)*\n  - Fits generalized linear models, including logistic regression when using the binomial family.\n- `summary()` *(base R)*\n  - Summarizes logistic regression output, including coefficients, standard errors, and p-values.\n- `exp()` *(base R)*\n  - Converts log-odds coefficients into odds ratios for interpretation.\n- `predict()` *(stats)*\n  - Generates predicted probabilities or classifications from a fitted logistic regression model.\n- `sample.split()` *(caTools)*\n  - Splits data into training and testing sets for model validation.\n- `confusionMatrix()` *(caret)*\n  - Evaluates classification performance using accuracy, sensitivity, specificity, and related metrics.\n- `pR2()` *(pscl)*\n  - Computes pseudo R² measures (e.g., McFadden’s R²) for logistic regression models.\n- `varImp()` *(caret)*\n  - Assesses the relative importance of predictors in a classification model.\n- `vif()` *(car)*\n  - Detects multicollinearity among predictors using variance inflation factors.\n- `roc()` *(pROC)*\n  - Constructs a Receiver Operating Characteristic (ROC) curve to evaluate classification performance.\n- `auc()` *(pROC)*\n  - Calculates the Area Under the ROC Curve (AUC) as a summary measure of model discrimination.\n\n## Example APA-style Write-up {#sec-log-reg-apa}\n\nThe following example demonstrates one acceptable way to report the results of a logistic regression analysis in APA style.\n\n**Logistic Regression**\n\nA logistic regression analysis was conducted to examine whether credit card balance, income, and student status predicted the likelihood of default. The overall logistic regression model was statistically significant, $\\chi^2(3) = 428.52, p < .001$, and demonstrated good model fit, as indicated by McFadden’s pseudo-$R^2 = .46$. Higher credit card balances were associated with increased odds of default, whereas students had significantly lower odds of default than non-students. Income was not a significant predictor after accounting for balance and student status.\n\n## 💡 *Reproducibility Tip:* {#sec-log-reg-tip}\n\nWhen evaluating predictive models, results can change depending on how the data are split into training and testing sets. To make your results reproducible, always control randomness and clearly document your modeling choices.\n\nUsing `set.seed()` (like in the reproducibility tip found in @sec-anova-tip) ensures that the same observations are assigned to the training and test sets each time the code is run. In addition, choices such as the train/test split ratio and classification threshold (e.g., 0.5) should be explicitly stated, as they directly affect model performance.\n\nPredictive results are only reproducible when both the code *and the evaluation decisions* are transparent.\n",
    "supporting": [
      "09-Logistic-Regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}