{
  "hash": "7d337c60f263efe9752da06e330d418d",
  "result": {
    "engine": "knitr",
    "markdown": "# Analyzing Categorical Data {#sec-cat-analysis}\n\n## Introduction {#sec-intro-cat-analysis}\n\nIn some situations, we do not have numerical data, and only categorical data. What do we do then? There are no meaningful measures of central tendency like the mean, median, or mode. We can't make a scatterplot, or run a correlation matrix, or other techniques we have covered in this textbook so far.\n\nIn situations like these, when we **only** have categorical values, we undergo a *Categorical Analysis.* Today, we will be looking at three different treatment options aimed at inhibiting infections.\n\n::: callout-note\n### In this lesson, the question we are trying to answer is:\n\n*Does the type of treatment people get affect whether they get an infection?*\n:::\n\nWe'll use a dataset called `infection_treatments`. Each row is a unique participant, indicating what treatment method they utilized, and if they became infected or not.\n\n## Learning Objectives {#sec-cat-objectives}\n\nBy the end of this chapter, you will be able to:\n\n- Identify situations in which categorical analysis is appropriate and numerical methods are not\n- Load and inspect categorical data to confirm variable types and structure\n- Create and interpret contingency tables using base R and tidyverse tools\n- Calculate and interpret row- and column-based percentages for categorical data\n- Visualize relationships between categorical variables using stacked and grouped bar charts\n- Conduct and interpret a chi-square test of independence using `chisq.test()`\n- Explain the role of expected counts, degrees of freedom, and p-values in chi-square testing\n- Use residuals and standardized residuals to identify cells that contribute most to a chi-square result\n- Quantify the strength of association between categorical variables using Cramer’s V\n\n## Loading Our Data {#sec-cat-analysis-data}\n\nThis chapter uses the `infection_treatment` dataset from the companion R `reproresearchR` package (@R-reproresearchR). Refer back to @sec-reproresearchR-package to find out more about the `reproresearchR` package if needed.\n\nInstead of using the `summary()` or `str()` functions, we are going to experiment with the `skim()` function from the `skimr` package (@R-skimr) to investigate our data.\n\n\n::: {#tbl-loading-data .cell tbl-cap='The skim function from the skimr package provides with important information regarding our data.'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(reproresearchR)\n\ninfection <- reproresearchR::infection_treatments\n\nlibrary(skimr)\n\nskim(infection)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |          |\n|:------------------------|:---------|\n|Name                     |infection |\n|Number of rows           |150       |\n|Number of columns        |2         |\n|_______________________  |          |\n|Column type frequency:   |          |\n|character                |2         |\n|________________________ |          |\n|Group variables          |None      |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|Infection     |         0|             1|   2|   3|     0|        2|          0|\n|Treatment     |         0|             1|   7|  13|     0|        3|          0|\n\n\n:::\n:::\n\n\nWe can see our data nice and loaded. There are two columns, Infection and Treatment which are both categorical, and there are 150 rows. Thankfully, we do not have any missing data. Let's dig a little deeper into our data.\n\n## Contingency Tables {#sec-contingency-tables}\n\nWhen there are only categorical variables, we need to create what are called contingency table (otherwise known as frequency tables). We first touched upon contingency tables in @sec-tidyverse-insights-count, where we used the `table()` command from base r and the `count()` function from `dplyr/tidyverse`. In addition, the the `xtabs` command from the `stats` package can also be used. It is personal preference on which you decide to personally use.\n\nFirst, we check the balance of our groups to ensure the randomization worked and to see the overall infection rate. We can start with using `table()`.\n\n\n::: {#tbl-treatment-counts .cell tbl-cap='Frequency of participants per Treatment group.'}\n\n```{.r .cell-code}\n# All three are at the same frequency\ntable(infection$Treatment)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      Control     Cranberry Lactobacillus \n           50            50            50 \n```\n\n\n:::\n:::\n\n\nUsing the `count()` function, we can perform essentially the same thing.\n\n\n::: {#tbl-infection-counts .cell tbl-cap='Total count of Infected vs. Non-Infected participants.'}\n\n```{.r .cell-code}\n# Showing there are more people that were not infected vs infected\ninfection |> count(Infection)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  Infection     n\n  <chr>     <int>\n1 No          104\n2 Yes          46\n```\n\n\n:::\n:::\n\n\nNow, we combine these two variables to see how infection status is distributed across the different treatments. While `table()` works, we will use `xtabs()` for a cleaner, formula-based approach.\n\n\n::: {#tbl-contingency-main .cell tbl-cap='Contingency Table: Infection Status by Treatment Group.'}\n\n```{.r .cell-code}\nlibrary(knitr)\n\n# Create the table using the xtabs command\ncontingency_table <- xtabs(~Treatment + Infection, data = infection)\n\nkable(contingency_table, caption = \"Contingency table displaying the frequency of infection status across treatment groups.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Contingency table displaying the frequency of infection status across treatment groups.\n\n|              | No| Yes|\n|:-------------|--:|---:|\n|Control       | 32|  18|\n|Cranberry     | 42|   8|\n|Lactobacillus | 30|  20|\n\n\n:::\n:::\n\n\nIn R formulas, the variable before the + becomes the rows, and the variable after the + becomes the columns. If we reverse the formula, we transpose the table.\n\n\n::: {#tbl-contingency-reversed .cell tbl-cap='Reversed Contingency Table: Treatment Group by Infection Status.'}\n\n```{.r .cell-code}\n# Reversing the formula to see the change in orientation\nreverse_table <- xtabs(~Infection + Treatment, data = infection)\n\nkable(reverse_table, caption = \"Contingency table displaying the same infection data with rows and columns reversed to illustrate how formula order affects table orientation.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Contingency table displaying the same infection data with rows and columns reversed to illustrate how formula order affects table orientation.\n\n|    | Control| Cranberry| Lactobacillus|\n|:---|-------:|---------:|-------------:|\n|No  |      32|        42|            30|\n|Yes |      18|         8|            20|\n\n\n:::\n:::\n\n\nNow through any of the ways (table or xtabs), we are able to see that *Cranberry* has the lowest number infected out of the three treatments. What if we want to understand this from a percentage standpoint?\n\n**Let's find out.**\n\nWe will call on the help of the `janitor` package (@R-janitor), specifically the `tabyl()`, `adorn_totals()`, `adorn_percentages()`, `adorn_pct_formatting()`, and `adorn_ns()` functions.\n\n\n::: {#tbl-percentages-CA .cell tbl-cap='Contingency Table of Infection by Treatment Group: Combined Row Percentages and Sample Sizes (n).'}\n\n```{.r .cell-code}\nlibrary(janitor)\n\nc_table <- infection |>\n  tabyl(Treatment, Infection) |>         # Makes a contingency table\n  adorn_totals(\"row\") |>                 # Adds totals for each treatment\n  adorn_percentages(\"row\") |>            # Adds row percentages\n  adorn_pct_formatting(digits = 1) |>    # Makes it readable (adds % signs)\n  adorn_ns()                              # Combines counts + percentages\n\nkable(c_table, caption = \"Distribution of infection status within each treatment group, reported as row percentages with counts (n).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Distribution of infection status within each treatment group, reported as row percentages with counts (n).\n\n|Treatment     |No          |Yes        |\n|:-------------|:-----------|:----------|\n|Control       |64.0%  (32) |36.0% (18) |\n|Cranberry     |84.0%  (42) |16.0%  (8) |\n|Lactobacillus |60.0%  (30) |40.0% (20) |\n|Total         |69.3% (104) |30.7% (46) |\n\n\n:::\n:::\n\n\nFrom a percentage standpoint, we see that 84% of people who were given *cranberries* were not infected! That is much higher than either other treatment options, and the total percentage of people who were not infected as well.\n\nIt seems that **cranberry** is taking an early lead in terms of which treatment is the most impactful. We have some preliminary numbers, so now we can visualize.\n\n## Visualizations {#sec-cat-analysis-viz}\n\nWith purely categorical data, the visualization most commonly recommended would be a *bar chart.* With a bar chart, a viewer can interpret differences between the variables. There are two main options, a **stacked** or **grouped** bar chart. The main difference from a coding perspective is what we enter inside the `geom_bar` command.\n\n::: callout-tip\n### Adding Flavor to Your Visualizations\n\nIf you’d like to enhance the aesthetic of your plots, consider using the `ggthemes` package (@R-ggthemes). It provides a variety of alternative themes that can quickly change the look and feel of your graphics.\n\nThe examples below use `theme_solarized()` and `theme_classic()`, but many additional options are available. Explore and experiment — just be sure your styling choices support clarity and suit your audience.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We can use the library ggthemes to add some flavor to our plots\nlibrary(ggthemes)\n\n# Creating a stacked bar chart\nstacked <- ggplot(infection, aes(x = Treatment, fill = Infection)) +\n  geom_bar(position = \"fill\") +   # \"fill\" stacks to 100% height\n  labs(\n    title = \"Proportion of Infections by Treatment Type\",\n    y = \"Proportion of Participants\",\n    x = \"Treatment\"\n  ) +\n  theme_solarized()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating a grouped bar chart\ngrouped <- ggplot(infection, aes(x = Treatment, fill = Infection)) +\n  geom_bar(position = \"dodge\") +\n  geom_text(\n    stat = \"count\",                          # use counts from geom_bar\n    aes(label = after_stat(count)),          # label each bar with its count\n    position = position_dodge(width = 0.9),  # place correctly over side-by-side bars\n    vjust = -0.3,                            # move labels slightly above bars\n    size = 4\n  ) +\n  labs(\n    title = \"Number of Infections by Treatment Type\",\n    x = \"Treatment\",\n    y = \"Count of Participants\",\n    fill = \"Infection Outcome\"\n  ) +\n  theme_classic()\n```\n:::\n\n\nUsing the `patchwork` package (@R-patchwork), we can add two or more plots together using the `+` symbol.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We can put them side by side to compare what they look like\nlibrary(patchwork)\n\ngrouped + stacked + plot_annotation(title = \"Visualizing Infection Outcomes by Treatment (Stacked Vs. Grouped\")\n```\n\n::: {.cell-output-display}\n![Side-by-side comparison of stacked and grouped bar charts visualizing infection outcomes by treatment type. The stacked chart emphasizes proportional differences, while the grouped chart highlights raw counts. Together, these plots illustrate how different visual encodings can influence interpretation of categorical data.](06-Analyzing-Categorical-Data_files/figure-html/fig-grouped-stacked-patchwork-1.png){#fig-grouped-stacked-patchwork width=672}\n:::\n:::\n\n\nTo make our graphs more interactive with our users, we can utilize the `ggplotly()` function from the `plotly` package (@R-plotly) (@R-webshot2).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We can also use the plotly package to make the visual more interactive\nlibrary(plotly)\n\nggplotly(grouped)\n```\n\n::: {#fig-plotly-graph .cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-19196f2f194609e3b43f\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-19196f2f194609e3b43f\">{\"x\":{\"data\":[{\"orientation\":\"v\",\"width\":[0.44999999999999996,0.45000000000000018,0.45000000000000018],\"base\":[0,0,0],\"x\":[0.77500000000000002,1.7749999999999999,2.7749999999999999],\"y\":[32,42,30],\"text\":[\"count: 32<br />Treatment: Control<br />Infection: No\",\"count: 42<br />Treatment: Cranberry<br />Infection: No\",\"count: 30<br />Treatment: Lactobacillus<br />Infection: No\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(248,118,109,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"transparent\"}},\"name\":\"No\",\"legendgroup\":\"No\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.45000000000000018,0.45000000000000018,0.45000000000000018],\"base\":[0,0,0],\"x\":[1.2250000000000001,2.2250000000000001,3.2250000000000001],\"y\":[18,8,20],\"text\":[\"count: 18<br />Treatment: Control<br />Infection: Yes\",\"count:  8<br />Treatment: Cranberry<br />Infection: Yes\",\"count: 20<br />Treatment: Lactobacillus<br />Infection: Yes\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,191,196,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"transparent\"}},\"name\":\"Yes\",\"legendgroup\":\"Yes\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.77500000000000002,1.7749999999999999,2.7749999999999999],\"y\":[32,42,30],\"text\":[32,42,30],\"hovertext\":[\"count: 32<br />Treatment: Control<br />Infection: No<br />count: 32\",\"count: 42<br />Treatment: Cranberry<br />Infection: No<br />count: 42\",\"count: 30<br />Treatment: Lactobacillus<br />Infection: No<br />count: 30\"],\"textfont\":{\"size\":15.118110236220474,\"color\":\"rgba(0,0,0,1)\"},\"type\":\"scatter\",\"mode\":\"text\",\"hoveron\":\"points\",\"name\":\"No\",\"legendgroup\":\"No\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.2250000000000001,2.2250000000000001,3.2250000000000001],\"y\":[18,8,20],\"text\":[18,8,20],\"hovertext\":[\"count: 18<br />Treatment: Control<br />Infection: Yes<br />count: 18\",\"count:  8<br />Treatment: Cranberry<br />Infection: Yes<br />count:  8\",\"count: 20<br />Treatment: Lactobacillus<br />Infection: Yes<br />count: 20\"],\"textfont\":{\"size\":15.118110236220474,\"color\":\"rgba(0,0,0,1)\"},\"type\":\"scatter\",\"mode\":\"text\",\"hoveron\":\"points\",\"name\":\"Yes\",\"legendgroup\":\"Yes\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":40.840182648401829,\"r\":7.3059360730593621,\"b\":37.260273972602747,\"l\":37.260273972602747},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"title\":{\"text\":\"Number of Infections by Treatment Type\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.534246575342465},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,3.6000000000000001],\"tickmode\":\"array\",\"ticktext\":[\"Control\",\"Cranberry\",\"Lactobacillus\"],\"tickvals\":[1,2,3],\"categoryorder\":\"array\",\"categoryarray\":[\"Control\",\"Cranberry\",\"Lactobacillus\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(0,0,0,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Treatment\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-2.1000000000000001,44.100000000000001],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"10\",\"20\",\"30\",\"40\"],\"tickvals\":[0,10,20,30,40],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"10\",\"20\",\"30\",\"40\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(0,0,0,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Count of Participants\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"layer\":\"below\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"Infection Outcome\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"30585320405f\":{\"x\":{},\"fill\":{},\"type\":\"bar\"},\"30586a62479b\":{\"x\":{},\"fill\":{},\"label\":{}}},\"cur_data\":\"30585320405f\",\"visdat\":{\"30585320405f\":[\"function (y) \",\"x\"],\"30586a62479b\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nInteractive grouped bar chart displaying counts of infection outcomes by treatment type. Interactivity allows users to hover over bars to inspect values directly, supporting exploratory analysis while preserving the same information shown in the static grouped bar chart.\n:::\n:::\n\n\n::: callout-note\n### When using ggplotly:\n\nMove your cursor over the bars to gather more insights about your graph/data.\n:::\n\n## Chi-Square Test {#sec-chi-square}\n\nNow, we have done some investigation on our data through contingency tables and visualizations. It is time to run what is called a **chi-square** test. This allows us to see if two categorical variables are related to each other.\n\n\n::: {#tbl-chisq_test .cell tbl-cap='Chi-Square Test of Independence: Assessing the Relationship between Treatment Group and Infection Status.'}\n\n```{.r .cell-code}\nchisq.test(contingency_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  contingency_table\nX-squared = 7.7759, df = 2, p-value = 0.02049\n```\n\n\n:::\n:::\n\n\nWhether we performed it on our contingency table, we get:\n\n1.  X\\^2- This is the test statistic. This is telling us how much different our observed is vs our expected.\n2.  df - Degrees of freedom = (rows - 1)*(columns - 1). For 3 treatments and 2 outcomes, df = (3-1)*(2-1) = 2.\n3.  p-value- This tells us if it is statistically significant or not.\n\nWe see that our X\\^2 value is 7.78, our df is 2, and our p-value is 0.0204871. Since our p-value is less than .05, we can rightly say that there is a significant relationship between treatment plans and outcomes.\n\nNow that we know it is significant, we need to dive a little deeper. We are understanding that **cranberry** is looking like the leader, but we can become more solidified on that stance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchi_square_test <- chisq.test(contingency_table)\n\n# All the parts of the chi square can be called.\nchi_square_test$statistic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nX-squared \n  7.77592 \n```\n\n\n:::\n\n```{.r .cell-code}\nchi_square_test$parameter\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndf \n 2 \n```\n\n\n:::\n\n```{.r .cell-code}\nchi_square_test$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0204871\n```\n\n\n:::\n\n```{.r .cell-code}\nchi_square_test$method\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Pearson's Chi-squared test\"\n```\n\n\n:::\n\n```{.r .cell-code}\nchi_square_test$data.name\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"contingency_table\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# What our data already is\nchi_square_test$observed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Infection\nTreatment       No Yes\n  Control       32  18\n  Cranberry     42   8\n  Lactobacillus 30  20\n```\n\n\n:::\n\n```{.r .cell-code}\n# What our data would look like if there was no relationship\nchi_square_test$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Infection\nTreatment             No      Yes\n  Control       34.66667 15.33333\n  Cranberry     34.66667 15.33333\n  Lactobacillus 34.66667 15.33333\n```\n\n\n:::\n\n```{.r .cell-code}\n# Difference between observed and expected\n# Positive is more than expected\n# Negative is less than expected\n# Bigger number = bigger difference\n# Represent how many standard deviations\nchi_square_test$residuals\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Infection\nTreatment               No        Yes\n  Control       -0.4529108  0.6810052\n  Cranberry      1.2455047 -1.8727644\n  Lactobacillus -0.7925939  1.1917591\n```\n\n\n:::\n\n```{.r .cell-code}\n# Standard Residuals\n# More like an actual z-score\nchi_square_test$stdres\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Infection\nTreatment              No       Yes\n  Control       -1.001671  1.001671\n  Cranberry      2.754595 -2.754595\n  Lactobacillus -1.752924  1.752924\n```\n\n\n:::\n:::\n\n\n::: callout-tip\n### Rule of Thumb:\n\nThink of standardized residuals like z-scores: values greater than +2 or less than -2 are the 'statistically interesting' parts of your table that are driving your p-value.\n:::\n\nWe can also visualize our observed versus our expected counts, as visualizations are *key* to understanding our data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Extract observed and expected counts from our test object\nobs_exp_data <- data.frame(\n  Treatment = rep(rownames(chi_square_test$observed), 2),\n  Infection = rep(colnames(chi_square_test$observed), each = 3),\n  Observed = as.vector(chi_square_test$observed),\n  Expected = as.vector(chi_square_test$expected)\n)\n\n# 2. Pivot the data to a 'long' format for ggplot\nplot_data <- obs_exp_data |>\n  pivot_longer(cols = c(Observed, Expected), \n               names_to = \"Type\", \n               values_to = \"Counts\")\n\n# 3. Create the plot\nggplot(plot_data, aes(x = Treatment, y = Counts, fill = Type)) +\n  geom_bar(stat = \"identity\", position = \"dodge\", alpha = 0.8) +\n  facet_wrap(~Infection) +\n  scale_fill_manual(values = c(\"Expected\" = \"grey70\", \"Observed\" = \"#CC0000\")) +\n  labs(\n    title = \"Observed vs. Expected Infection Counts\",\n    subtitle = \"The grey bars show what we would expect by random chance alone\",\n    x = \"Treatment Group\",\n    y = \"Number of Participants\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Comparison of Observed vs. Expected counts across treatment groups. The 'Expected' bars represent the distribution of infections if the null hypothesis were true (no relationship). The visible gap between the observed and expected bars in the Cranberry group illustrates the 'surprise' in the data that drives the significant Chi-Square result.](06-Analyzing-Categorical-Data_files/figure-html/fig-observed-vs-expected-1.png){#fig-observed-vs-expected width=672}\n:::\n:::\n\n\nOur deep dive uncovered some very important things about our experiment:\n\n- Expected: all of the values were different from what we the actual observations were. If there was no relationship between the two variables, it was expected that each treatment would have about 35 people not infected, and 15 people infected\n- Residuals/stdres: this is where we really start to tie everything together. With the residuals, we are looking for if it is positive/negative, and then strength in relation to the other. **Cranberry** if the only one of the three where there are less people infected than anticipated, almost 2 standard deviations less than expected. Both other treatments have more people infected than expected.\n  - Note: Standardized residuals behave like z-scores — values beyond ±2 suggest cells contributing most strongly to the overall χ² statistic.\n\nWe tie this information together to get a very strong case for **cranberry.** There is just one piece of the puzzle left to bring this home.\n\n## Cross Tables {#sec-cross-tables}\n\nIn the `gmodels` package (@R-gmodels) we are able to utilize the `CrossTable()` command. *Beware*, this can at first be overwhelming, as a lot of information is thrown at you.\n\n\n::: {#tbl-crosstables .cell tbl-cap='Comprehensive Cross-Tabulation: Observed and Expected Frequencies, Row/Column Proportions, and Chi-Square Contributions by Treatment and Infection Status.'}\n\n```{.r .cell-code}\nlibrary(gmodels)\n\n# This allows us to see the contributions each category has on chi-square.\n# Note, you (infection$Treatment, infection$Infection) if you want to stick to defaults\nCrossTable(infection$Treatment, infection$Infection,\n           prop.chisq = TRUE,    # Shows the chi-square contribution\n           chisq = TRUE,         # shows chi-square test\n           expected = TRUE,      # shows expected counts\n           prop.r = TRUE,        # shows row proportions\n           prop.c = TRUE)        # shows column proportions\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n \n   Cell Contents\n|-------------------------|\n|                       N |\n|              Expected N |\n| Chi-square contribution |\n|           N / Row Total |\n|           N / Col Total |\n|         N / Table Total |\n|-------------------------|\n\n \nTotal Observations in Table:  150 \n\n \n                    | infection$Infection \ninfection$Treatment |        No |       Yes | Row Total | \n--------------------|-----------|-----------|-----------|\n            Control |        32 |        18 |        50 | \n                    |    34.667 |    15.333 |           | \n                    |     0.205 |     0.464 |           | \n                    |     0.640 |     0.360 |     0.333 | \n                    |     0.308 |     0.391 |           | \n                    |     0.213 |     0.120 |           | \n--------------------|-----------|-----------|-----------|\n          Cranberry |        42 |         8 |        50 | \n                    |    34.667 |    15.333 |           | \n                    |     1.551 |     3.507 |           | \n                    |     0.840 |     0.160 |     0.333 | \n                    |     0.404 |     0.174 |           | \n                    |     0.280 |     0.053 |           | \n--------------------|-----------|-----------|-----------|\n      Lactobacillus |        30 |        20 |        50 | \n                    |    34.667 |    15.333 |           | \n                    |     0.628 |     1.420 |           | \n                    |     0.600 |     0.400 |     0.333 | \n                    |     0.288 |     0.435 |           | \n                    |     0.200 |     0.133 |           | \n--------------------|-----------|-----------|-----------|\n       Column Total |       104 |        46 |       150 | \n                    |     0.693 |     0.307 |           | \n--------------------|-----------|-----------|-----------|\n\n \nStatistics for All Table Factors\n\n\nPearson's Chi-squared test \n------------------------------------------------------------\nChi^2 =  7.77592     d.f. =  2     p =  0.0204871 \n\n\n \n```\n\n\n:::\n:::\n\n\n`CrossTable` gave us a lot of information (nothing we can not handle). Thankfully, there is an legend in the beginning of the results that identifies what each number is. Some of these we already discovered, such as expected values and the chi-square X\\^2 value, but also some new information. Specifically, we are able to see the chi-square contribution. To break this down:\n\n- When we run the chi-square test, we get the X\\^2 value. Importantly, each combination of the variables contributes **individually** to this number. We are looking for the biggest contributors to not only understand the chi-square value better, but to also understand what is the most impactful.\n- For this result, our third number's in each cell are the *chi-square contribution.* It is evident that **cranberry** has the highest contribution to the chi-square test statistic.\n\n## Contribution {#sec-cat-analysis-contribution}\n\nIf we want to hone in on this more, we can take the contributions and turn them into percentages.\n\n::: callout-tip\n### To find out more about the X\\^2 value, it is important to answer the question:\n\nWhat percentage of the X\\^2 value is each contribution responsible for?\n:::\n\n\n::: {#tbl-contributions .cell tbl-cap='Cell-wise Contributions to the Chi-Square Statistic: Identifying Discrepancies Between Observed and Expected Frequencies.'}\n\n```{.r .cell-code}\n# Calculate contribution to chi-square statistic\ncontributions <- ((chi_square_test$observed-chi_square_test$expected)^2)/chi_square_test$expected\n\ncontributions\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Infection\nTreatment              No       Yes\n  Control       0.2051282 0.4637681\n  Cranberry     1.5512821 3.5072464\n  Lactobacillus 0.6282051 1.4202899\n```\n\n\n:::\n:::\n\n\n::: callout-tip\n### The formula for calculating the chi-square statistic is:\n\n$$X^2= ((observed-expected)^2)/expected$$\n:::\n\n\n::: {#tbl-percent-contributions .cell tbl-cap='Percentage of Total Chi-Square Variance by Cell: Quantifying the Relative Impact of Each Treatment on the Overall Significance.'}\n\n```{.r .cell-code}\npercent_contributions <- contributions / chi_square_test$statistic * 100\n\npercent_contributions\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Infection\nTreatment              No       Yes\n  Control        2.637993  5.964158\n  Cranberry     19.949821 45.103943\n  Lactobacillus  8.078853 18.265233\n```\n\n\n:::\n:::\n\n\nThrough this, we discovered that about **65%** of the X\\^2 value is due to the **cranberry** treatment.\n\nYou already know that visualizations really help paint the picture, and *chi-square contributions* are not exempt. For this, the `pheatmap` package (@R-pheatmap) comes in handy with the `pheatmap()` function..\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pheatmap)\n\n# Create heatmap for percentage contributions\npheatmap(percent_contributions,\n         display_numbers = TRUE,\n         cluster_rows = FALSE,\n         cluster_cols = FALSE,\n         main = \"% Contribution to Chi-Square Statistic\")\n```\n\n::: {.cell-output-display}\n![Heatmap showing the percentage contribution of each cell to the overall chi-square statistic. Darker shading indicates cells that contribute more strongly to the chi-square value, highlighting which combinations of treatment type and infection outcome drive the observed association. This visualization helps identify where deviations from expected counts are largest following a significant chi-square test.](06-Analyzing-Categorical-Data_files/figure-html/fig-pheatmap-1.png){#fig-pheatmap width=672}\n:::\n:::\n\n\nThat glaring, deep red box? That is the **cranberry** yes cell!\n\nTying all of this together, we have discovered:\n\n1.  **Cranberry** has the most people that were not infected (least amount infected).\n2.  The **chi-square** test shows a significant relationship between treatment and outcome.\n3.  When looking at residuals, **cranberry** was the only treatment with less people infected than expected.\n4.  When looking at *chi-square contributions,* **cranberry** had the largest contribution, with about **65%** of the test statistic being accounted for by **cranberry.**\n\nNow, how impactful is this overall? What is the **effect** of treatment overall on outcome?\n\n## CramerV {#sec-cramer-v}\n\nCramer’s V tells you the strength of the relationship between two categorical variables, similar to correlation coefficient It is important to note that this measures effect size. This is **not** a statistic. We can utilize the `cramerV()` command from the `rcompanion` package (@R-rcompanion).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rcompanion)\n\ncramerV(contingency_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCramer V \n  0.2277 \n```\n\n\n:::\n:::\n\n\nThe value derived from this is **0.23**. Again, similar to the correlation coefficient, there are guidelines that can be utilized to understand the strength.\n\n\n::: {#tbl-cramerV-guidlines .cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Guidelines for interpreting the strength of association using Cramer’s *V*. These ranges provide general heuristics for describing effect size in categorical analyses and should be interpreted in context rather than as strict cutoffs.</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Cramer V Value </th>\n   <th style=\"text-align:left;\"> Strength of Relationship </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 0.00–0.10 </td>\n   <td style=\"text-align:left;\"> Very Weak </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 0.10–0.30 </td>\n   <td style=\"text-align:left;\"> Weak </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 0.30–0.50 </td>\n   <td style=\"text-align:left;\"> Moderate </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> &gt;0.50 </td>\n   <td style=\"text-align:left;\"> Strong </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nTreatment, overall, had a weak-moderate effect on outcome overall. This suggests that while treatment type and infection outcome are related, the relationship isn’t strong — meaning that other factors likely play a larger role.\n\n## Interpretation {#sec-cat-analysis-interpretation}\n\n- The chi-square test shows X\\^2 = 7.78, df = 2, p = 0.02\n- This means there is a statistically significant relationship between Treatment and Infection.\n- The Cranberry group had fewer infections than expected and contributes most to the chi-square statistic.\n- Cramer’s V shows the relationship is weak-to-moderate in strength.\n- **Drink your cranberry juice!**\n\n## Key Takeaways {#sec-cat-analysis-takeaways}\n\n- The Chi-Square test helps us determine whether two categorical variables are related.\n- It compares the **observed** frequencies (what we saw) to the **expected** frequencies (what we’d expect by chance).\n- A large Chi-Square statistic and a p-value \\< .05 suggest that the relationship is **statistically significant**.\n- Degrees of freedom (df) are based on the number of categories: (rows - 1) \\* (columns - 1).\n- Cramer’s V measures the *strength* of the relationship, similar to a correlation coefficient:\n  - 0.00–0.10 = very weak \\| 0.10–0.30 = weak \\| 0.30–0.50 = moderate \\| \\>0.50 = strong\n- Residuals show which specific groups contribute most to the Chi-Square result.\n- Visualizations (like bar charts or heatmaps) make it easier to interpret where the differences lie.\n- Statistical significance ≠ practical significance — even weak relationships can be significant with large samples.\n- Example takeaway: Cranberry treatment showed fewer infections than expected — a weak but meaningful effect!\n\n## Checklist {#sec-cat-analysis-checklist}\n\n**When running a Chi-Square test, have you:**\n\n- [ ] Identified both variables as **categorical** (not numeric)?\n- [ ] Created a **contingency table** to summarize the counts?\n- [ ] Calculated **expected counts** to compare against observed values?\n- [ ] Verified that no expected counts are too small (all \\> 5 is ideal)?\n- [ ] Visualized your data (stacked/grouped bar charts)?\n- [ ] Interpreted the Chi-Square statistic, df, and p-value?\n- [ ] Calculated **Cramer’s V** to assess the strength of association?\n- [ ] Checked which cells contribute most using **standardized residuals**?\n- [ ] (Optional) Created a **heatmap** to visualize contributions or residuals?\n- [ ] Written a clear interpretation that answers your research question?\n\n## Key Functions & Commands {#sec-cat-analysis-key-functions}\n\nThe following functions and commands are introduced or reinforced in this chapter to support categorical data analysis, contingency tables, and Chi-Square testing.\n\n- `table()` *(base R)*\n  - Creates basic contingency (frequency) tables for categorical variables.\n- `xtabs()` *(base R)*\n  - Constructs contingency tables using a formula interface, useful for multi-way tables.\n- `tabyl()` *(janitor)*\n  - Generates clean contingency tables that integrate easily with percentage calculations.\n- `adorn_percentages()` *(janitor)*\n  - Converts contingency table counts into row- or column-based percentages.\n- `adorn_ns()` *(janitor)*\n  - Displays counts and percentages together for clearer interpretation.\n- `chisq.test()` *(stats)*\n  - Performs a Chi-Square test of independence to assess whether two categorical variables are related.\n- `CrossTable()` *(gmodels)*\n  - Produces detailed cross-tabulations including expected counts, proportions, and chi-square contributions.\n- `pheatmap()` *(pheatmap)*\n  - Visualizes Chi-Square contributions or residuals using a heatmap.\n- `cramerV()` *(rcompanion)*\n  - Computes Cramer’s V to measure the strength of association between categorical variables.\n\n## Example APA-style Write-up {#sec-cat-analysis-apa}\n\nThe following example demonstrates one acceptable way to report the results of a chi-square test of independence in APA style.\n\n**Chi-Square Test of Independence**\n\nA chi-square test of independence indicated a significant association between treatment type and infection outcome, $\\chi^2(2, N = 150) = 7.78, p = .02$. The strength of this association was weak-to-moderate, Cramer’s $V = .23$. As illustrated in @fig-pheatmap, the primary driver of this significance was the Cranberry group, which exhibited fewer infections than would be expected by chance.\n\n## 💡 *Reproducibility Tip:* {#sec-cat-tip}\n\nIt is essential to both visually *and* structurally inspect your data, because data are not always what they seem.\n\nConsider Advanced Placement (AP) exam scores in U.S. high schools. Students receive scores from 1 to 5. While these values look numeric, they are actually **categorical**—there is no meaningful value like 2.5. Treating them as numeric can lead to incorrect analyses. The same issue commonly arises with variables like zip codes, which may be stored as numbers but represent categories, not quantities.\n\nAlthough functions like `View()` or `head()` are useful for visually checking your data, they do not reveal how R is interpreting each variable. Always use functions like `str()` to confirm that variables are stored with the correct data type before running an analysis.\n\nAnalyses based on incorrectly typed variables are not reproducible—because they are not valid to begin with.\n",
    "supporting": [
      "06-Analyzing-Categorical-Data_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../site_libs/plotly-binding-4.11.0/plotly.js\"></script>\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}